### ISSUE TITLE
helm dependency update panics on symlink

### ISSUE THREAD

**Issue by dastrobu** [helm/helm#10162]
# [SSCCE](http://www.sscce.org)
To reproduce, run:

```bash
helm create foo
helm create bar

echo '
dependencies:
  - name: bar
    version: 0.1.0
' >> foo/Chart.yaml

ln -s $(pwd)/bar foo/charts/bar

helm dependency update foo
```

It will fail with 
```
walk.go:74: found symbolic link in path: /.../foo/charts/bar resolves to /.../bar
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "pmd" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Dependency bar did not declare a repository. Assuming it exists in the charts directory
Deleting outdated charts
Could not verify foo/charts/bar for deletion: cannot load a directory (Skipping)panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x53b980d]

goroutine 1 [running]:
helm.sh/helm/v3/pkg/chart.(*Chart).Name(...)
	helm.sh/helm/v3/pkg/chart/chart.go:76
helm.sh/helm/v3/pkg/downloader.(*Manager).safeMoveDeps(0xc0001a90e0, {0xc000010088, 0x1, 0x57}, {0xc000befc70, 0xd}, {0xc000befc56, 0xa})
	helm.sh/helm/v3/pkg/downloader/manager.go:452 +0x48d
helm.sh/helm/v3/pkg/downloader.(*Manager).downloadAll(0xc0001a90e0, {0xc000010088, 0xc0004d2e20, 0x1})
	helm.sh/helm/v3/pkg/downloader/manager.go:371 +0x176b
helm.sh/helm/v3/pkg/downloader.(*Manager).Update(0xc0001a90e0)
	helm.sh/helm/v3/pkg/downloader/manager.go:201 +0x109
main.newDependencyUpdateCmd.func1(0xc00036c780, {0xc0004f42b0, 0x1, 0x1})
	helm.sh/helm/v3/cmd/helm/dependency_update.go:74 +0x35c
github.com/spf13/cobra.(*Command).execute(0xc00036c780, {0xc0004f4280, 0x1, 0x1})
	github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc00026b900)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	helm.sh/helm/v3/cmd/helm/helm.go:87 +0x234
```

Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.17"}
```

**Comment by bacongobbler** [comment]
In the example you provided, it is expected that the [user provides the `repository`](https://helm.sh/docs/chart_best_practices/dependencies/#repository-urls) field to inform the helm client that the chart foo depends on chart bar, which can be found at a particular directory.

Off the top of my head, your example should look something like this:

```
helm create foo
helm create bar

echo '
dependencies:
  - name: bar
    repository: file://../bar
    version: 0.1.0
' >> foo/Chart.yaml

ln -s $(pwd)/bar foo/charts/bar

helm dependency update foo
```

That will fix the warning "Dependency bar did not declare a repository." Because otherwise it assumes chart bar already exists in foo's charts directory.

Regardless, we should capture the stack trace and return an error gracefully. Please feel free to contribute a fix for this.

**Comment by bacongobbler** [comment]
Hmm... Perhaps this has to do with how Go loads and resolves symbolic links as opposed to regular files.

Did this work in prior versions?

**Comment by dastrobu** [comment]
@bacongobbler here is what helm used to do. Version 3.6.3 outputs
```.../foo/charts/bar resolves to /.../bar
Saving 1 charts
Dependency bar did not declare a repository. Assuming it exists in the charts directory
Deleting outdated charts
```
Helm 3.7.0 turned `Assuming it exists in the charts directory` into a panic.

**Comment by mitchello** [comment]
Would it be possible to have a fix before the 12th January 2022 (date of the milestone) ?

**Comment by yxxhero** [comment]
@dastrobu @mitchello PRs is welcome. Thanks very much.

**Comment by zonggen** [comment]
Can reproduce with given commands on `v3.7.0`.

```
$ helm dependency update foo

walk.go:74: found symbolic link in path: /home/abai/git/playground/foo/charts/bar resolves to /home/abai/git/playground/bar
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "openshift-helm-charts" chart repository
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Dependency bar did not declare a repository. Assuming it exists in the charts directory
Deleting outdated charts
Could not verify foo/charts/bar for deletion: cannot load a directory (Skipping)panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x23c22ce]

goroutine 1 [running]:
helm.sh/helm/v3/pkg/chart.(*Chart).Name(...)
        helm.sh/helm/v3/pkg/chart/chart.go:76
helm.sh/helm/v3/pkg/downloader.(*Manager).safeMoveDeps(0xc0001a15f0, 0xc000114028, 0x1, 0x1, 0xc002863ed0, 0xd, 0xc002863ec0, 0xa, 0x0, 0x0)
        helm.sh/helm/v3/pkg/downloader/manager.go:452 +0x46e
helm.sh/helm/v3/pkg/downloader.(*Manager).downloadAll(0xc0001a15f0, 0xc000114028, 0x1, 0x1, 0x0, 0x0)
        helm.sh/helm/v3/pkg/downloader/manager.go:371 +0x671
helm.sh/helm/v3/pkg/downloader.(*Manager).Update(0xc0001a15f0, 0xc0001a15f0, 0x2)
        helm.sh/helm/v3/pkg/downloader/manager.go:201 +0x1b7
main.newDependencyUpdateCmd.func1(0xc000481680, 0xc00048a000, 0x1, 0x1, 0x0, 0x0)
        helm.sh/helm/v3/cmd/helm/dependency_update.go:74 +0x1da
github.com/spf13/cobra.(*Command).execute(0xc000481680, 0xc00021c200, 0x1, 0x1, 0xc000481680, 0xc00021c200)
        github.com/spf13/cobra@v1.2.1/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000480c80, 0xc000115768, 0x1, 0xc000653f60)
        github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
        helm.sh/helm/v3/cmd/helm/helm.go:87 +0x27b
```

**Comment by Phil0ctetes** [comment]
Hi I am facing a similar issue as well when using `helm package . --dependency-update` to resolve charts from oci (azure). 
I have to use `helm dependency update` first to succeed with `helm package .`. 

```
$ helm version
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}

$ helm package . --dependency-update
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x185a9ba]

goroutine 1 [running]:
helm.sh/helm/v3/internal/experimental/registry.(*Client).Pull(0x0, 0xc000e10d70, 0x43, 0x0, 0x0, 0x0, 0x43, 0xc0012435e0, 0x44f0a5)
	helm.sh/helm/v3/internal/experimental/registry/client.go:235 +0x21a
helm.sh/helm/v3/pkg/getter.(*OCIGetter).get(0xc000d28b40, 0xc000e72700, 0x34, 0xc001243678, 0xc000e72700, 0x34)
	helm.sh/helm/v3/pkg/getter/ocigetter.go:57 +0x23b
helm.sh/helm/v3/pkg/getter.(*OCIGetter).Get(0xc000d28b40, 0xc000e72700, 0x34, 0xc00064b900, 0x7, 0x8, 0xc000d28b40, 0x0, 0x0)
	helm.sh/helm/v3/pkg/getter/ocigetter.go:36 +0x77
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo(0xc001243a98, 0xc0003a07d0, 0x34, 0xc0003a0805, 0x14, 0xc00082ccf0, 0x2d, 0x8, 0x0, 0x0, ...)
	helm.sh/helm/v3/pkg/downloader/chart_downloader.go:99 +0x142
helm.sh/helm/v3/pkg/downloader.(*Manager).downloadAll(0xc000197290, 0xc000562000, 0x3, 0x3, 0x0, 0x0)
	helm.sh/helm/v3/pkg/downloader/manager.go:360 +0xd95
helm.sh/helm/v3/pkg/downloader.(*Manager).Update(0xc000197290, 0xc000197290, 0x225ac48)
	helm.sh/helm/v3/pkg/downloader/manager.go:201 +0x1b7
main.newPackageCmd.func1(0xc0002a8a00, 0xc000680ca0, 0x1, 0x2, 0x0, 0x0)
	helm.sh/helm/v3/cmd/helm/package.go:99 +0x431
github.com/spf13/cobra.(*Command).execute(0xc0002a8a00, 0xc000680c80, 0x2, 0x2, 0xc0002a8a00, 0xc000680c80)
	github.com/spf13/cobra@v1.2.1/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc00050ec80, 0xc0005b2370, 0x1, 0xc000563f60)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
main.main()

$ helm dependency update
[...]
Update Complete. ⎈Happy Helming!⎈
Saving 3 charts
Downloading xxx from repo oci://xxx.azurecr.io/helm/xxx/main/
Pulled: xxx.azurecr.io/helm/xx/main/xxx:1000.0.0-preview.154
Digest: sha256:...
Downloading Downloading xxx from repo oci://xxx.azurecr.io/helm/xxx/main/
Pulled: xxx.azurecr.io/helm/xx/main/xxx:1000.0.0-preview.154
Digest: sha256:...
Downloading xxx from repo oci://xxx.azurecr.io/helm/xxx/main/
Pulled: xxx.azurecr.io/helm/xx/main/xxx:1000.0.0-preview.154
Digest: sha256:...
Deleting outdated charts

$ helm package .
Successfully packaged chart and saved it to: ...
```

**Comment by guice** [comment]
Add a +1 here as well. Running into this while running `-u` or any dependency update:

```
bash-5.1# helm dep update sample-service/
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "evps-charts" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 3 charts
Downloading evps-common from repo https://charts.pkg.{redacted}.com
Downloading evps-php from repo https://charts.pkg.{redacted}.com
Downloading evps-nginx from repo https://charts.pkg.{redacted}.com
Deleting outdated charts
Could not verify sample-service/charts/.gitignore for deletion: file 'sample-service/charts/.gitignore' does not appear to be a gzipped archive; got 'application/octet-stream' (Skipping)panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1a20f8e]

goroutine 1 [running]:
helm.sh/helm/v3/pkg/chart.(*Chart).Name(...)
        helm.sh/helm/v3/pkg/chart/chart.go:76
helm.sh/helm/v3/pkg/downloader.(*Manager).safeMoveDeps(0xc000184fc0, 0xc003496000, 0x3, 0x3, 0xc000a3bcf8, 0x18, 0xc000a3bcc8, 0x15, 0x2d, 0xc001ed8bd0)
        helm.sh/helm/v3/pkg/downloader/manager.go:452 +0x46e
helm.sh/helm/v3/pkg/downloader.(*Manager).downloadAll(0xc000184fc0, 0xc003496000, 0x3, 0x3, 0x0, 0x0)
        helm.sh/helm/v3/pkg/downloader/manager.go:371 +0x671
helm.sh/helm/v3/pkg/downloader.(*Manager).Update(0xc000184fc0, 0xc000184fc0, 0x3)
        helm.sh/helm/v3/pkg/downloader/manager.go:201 +0x1b7
main.newDependencyUpdateCmd.func1(0xc00029b180, 0xc00045a6e0, 0x1, 0x1, 0x0, 0x0)
        helm.sh/helm/v3/cmd/helm/dependency_update.go:74 +0x1da
github.com/spf13/cobra.(*Command).execute(0xc00029b180, 0xc00045a6c0, 0x1, 0x1, 0xc00029b180, 0xc00045a6c0)
        github.com/spf13/cobra@v1.2.1/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000523b80, 0xc0002f7018, 0x1, 0xc0005dff60)
        github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
        helm.sh/helm/v3/cmd/helm/helm.go:87 +0x27b
```

**Comment by bacongobbler** [comment]
Here's the source: https://github.com/helm/helm/blob/9fafb4ad6811afb017cc464b630be2ff8390ac63/pkg/downloader/manager.go#L445-L459

I would look at how the `existsInSourceDirectory` map is populated - seems like some files that are not charts are no longer being populated in that list.

As @yxxhero mentioned previously, contributions to fix this are most welcome.

**Comment by juckerf** [comment]
same issue with an `.gitkeep` file in `charts`. probably anything else than charts (respectively gzipped archives) are causing problems
