### ISSUE TITLE
[v2] repo update: runtime: out of memory

### ISSUE THREAD

**Issue by nodesocket** [helm/helm#10193]
Hello. First, I am aware I am running a really old version of Helm `v2.16.12`. Planning to upgrade to v3 shortly. However, just started seeing the following `runtime :out of memory` condition intermittently when running `repo update` and wanted to report and see if there is a solution. The virtual machine this is running on has 1 GB of memory so by no means a powerhorse, but surely enough memory to parse yaml files.

```bash
helm repo update

...Successfully got an update from the "fusionauth" chart repository
...Successfully got an update from the "datadog" chart repository
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x1900a03, 0x16)
	/usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sysMap(0xc024000000, 0x4000000, 0x2a5c878)
	/usr/local/go/src/runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x2a478e0, 0x1000000, 0x2a478e8, 0x800)
	/usr/local/go/src/runtime/malloc.go:715 +0x1cd
runtime.(*mheap).grow(0x2a478e0, 0x800, 0x0)
	/usr/local/go/src/runtime/mheap.go:1286 +0x11c
runtime.(*mheap).allocSpan(0x2a478e0, 0x800, 0x420100, 0x2a5c888, 0x200000000)
	/usr/local/go/src/runtime/mheap.go:1124 +0x6a0
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:871 +0x64
runtime.(*mheap).alloc(0x2a478e0, 0x800, 0x2a40101, 0x1)
	/usr/local/go/src/runtime/mheap.go:865 +0x81
runtime.largeAlloc(0xfffe00, 0x7ff0c9700101, 0x2a25c00)
	/usr/local/go/src/runtime/malloc.go:1152 +0x92
runtime.mallocgc.func1()
	/usr/local/go/src/runtime/malloc.go:1047 +0x46
runtime.systemstack(0x461a04)
	/usr/local/go/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1056

goroutine 28 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:330 fp=0xc01227ba58 sp=0xc01227ba50 pc=0x461b00
runtime.mallocgc(0xfffe00, 0x166b7e0, 0x726f7469736f7001, 0x70747468223a2279)
	/usr/local/go/src/runtime/malloc.go:1046 +0x895 fp=0xc01227baf8 sp=0xc01227ba58 pc=0x40c9a5
runtime.makeslice(0x166b7e0, 0x7ffe00, 0xfffe00, 0x222c222f6d6f632e)
	/usr/local/go/src/runtime/slice.go:49 +0x6c fp=0xc01227bb28 sp=0xc01227baf8 pc=0x44adcc
encoding/json.(*Decoder).refill(0xc005761b80, 0x22, 0x1)
	/usr/local/go/src/encoding/json/stream.go:159 +0x157 fp=0xc01227bb90 sp=0xc01227bb28 pc=0x5ce167
encoding/json.(*Decoder).readValue(0xc005761b80, 0x0, 0x0, 0x182bde0)
	/usr/local/go/src/encoding/json/stream.go:140 +0x1e8 fp=0xc01227bbe8 sp=0xc01227bb90 pc=0x5cde88
encoding/json.(*Decoder).Decode(0xc005761b80, 0x1600560, 0xc0101f1640, 0x16de420, 0xc00f041560)
	/usr/local/go/src/encoding/json/stream.go:63 +0x79 fp=0xc01227bc28 sp=0xc01227bbe8 pc=0x5cd969
k8s.io/helm/vendor/github.com/ghodss/yaml.jsonUnmarshal(0x1b3c3e0, 0xc011d57110, 0x17842e0, 0xc00072a000, 0x0, 0x0, 0x0, 0x8ce000, 0x0)
	/go/src/k8s.io/helm/vendor/github.com/ghodss/yaml/yaml.go:59 +0xe8 fp=0xc01227bc90 sp=0xc01227bc28 pc=0x67cb68
k8s.io/helm/vendor/github.com/ghodss/yaml.Unmarshal(0xc00347c000, 0x96225d, 0xfffe00, 0x17842e0, 0xc00072a000, 0x0, 0x0, 0x0, 0xc000430990, 0x96225d)
	/go/src/k8s.io/helm/vendor/github.com/ghodss/yaml/yaml.go:42 +0x24c fp=0xc01227bd40 sp=0xc01227bc90 pc=0x67c97c
k8s.io/helm/pkg/repo.loadIndex(0xc00347c000, 0x96225d, 0xfffe00, 0xc00347c000, 0x96225d, 0xfffe00)
	/go/src/k8s.io/helm/pkg/repo/index.go:302 +0xd9 fp=0xc01227bdf0 sp=0xc01227bd40 pc=0x9d1339
k8s.io/helm/pkg/repo.(*ChartRepository).DownloadIndexFile(0xc000366040, 0xc00033a270, 0x23, 0x2, 0x2)
	/go/src/k8s.io/helm/pkg/repo/chartrepo.go:134 +0x28e fp=0xc01227beb0 sp=0xc01227bdf0 pc=0x9cdf4e
main.updateCharts.func1(0xc000561fd0, 0xc000561fc8, 0x1b3ec40, 0xc0000b0008, 0xc0000aed40, 0x12, 0xc000561fc0, 0xc000366040)
	/go/src/k8s.io/helm/cmd/helm/repo_update.go:135 +0x243 fp=0xc01227bfa0 sp=0xc01227beb0 pc=0x1570983
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc01227bfa8 sp=0xc01227bfa0 pc=0x463a91
created by main.updateCharts
	/go/src/k8s.io/helm/cmd/helm/repo_update.go:127 +0x182

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc000561fd8)
	/usr/local/go/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc000561fd0)
	/usr/local/go/src/sync/waitgroup.go:130 +0x64
main.updateCharts(0xc000389d60, 0x4, 0x4, 0x1b3ec40, 0xc0000b0008, 0xc0000aed40, 0x12, 0x0, 0x0, 0x0)
	/go/src/k8s.io/helm/cmd/helm/repo_update.go:148 +0x1af
main.(*repoUpdateCmd).run(0xc0004927c0, 0x0, 0x0)
	/go/src/k8s.io/helm/cmd/helm/repo_update.go:115 +0x323
main.newRepoUpdateCmd.func1(0xc00001f680, 0x2a5a348, 0x0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/helm/cmd/helm/repo_update.go:74 +0x74
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).execute(0xc00001f680, 0x2a5a348, 0x0, 0x0, 0xc00001f680, 0x2a5a348)
	/go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:826 +0x453
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0006fa780, 0x2, 0x2, 0xc0006fa780)
	/go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:864
main.main()
	/go/src/k8s.io/helm/cmd/helm/helm.go:270 +0x7a

goroutine 18 [chan receive]:
k8s.io/helm/vendor/k8s.io/klog.(*loggingT).flushDaemon(0x2a24b20)
	/go/src/k8s.io/helm/vendor/k8s.io/klog/klog.go:1018 +0x8b
created by k8s.io/helm/vendor/k8s.io/klog.init.0
	/go/src/k8s.io/helm/vendor/k8s.io/klog/klog.go:404 +0x6c

goroutine 30 [running]:
	goroutine running on other thread; stack unavailable
created by main.updateCharts
	/go/src/k8s.io/helm/cmd/helm/repo_update.go:127 +0x182

goroutine 51 [IO wait]:
internal/poll.runtime_pollWait(0x7ff0ca41ce68, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc0004b2c98, 0x72, 0x10200, 0x1029d, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0004b2c80, 0xc000944000, 0x1029d, 0x1029d, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc0004b2c80, 0xc000944000, 0x1029d, 0x1029d, 0x203000, 0xc, 0xc000950047)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0000b0c88, 0xc000944000, 0x1029d, 0x1029d, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x8e
crypto/tls.(*atLeastReader).Read(0xc0006024a0, 0xc000944000, 0x1029d, 0x1029d, 0x4256, 0xc000950042, 0xc00059d9c8)
	/usr/local/go/src/crypto/tls/conn.go:760 +0x60
bytes.(*Buffer).ReadFrom(0xc0001133d8, 0x1b3c560, 0xc0006024a0, 0x40a375, 0x170af40, 0x1877580)
	/usr/local/go/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc000113180, 0x1b3e7e0, 0xc0000b0c88, 0x5, 0xc0000b0c88, 0x8)
	/usr/local/go/src/crypto/tls/conn.go:782 +0xec
crypto/tls.(*Conn).readRecordOrCCS(0xc000113180, 0x0, 0x0, 0xc00059dd38)
	/usr/local/go/src/crypto/tls/conn.go:589 +0x115
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:557
crypto/tls.(*Conn).Read(0xc000113180, 0xc0005ac000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1233 +0x15b
bufio.(*Reader).Read(0xc00007b680, 0xc0005962d8, 0x9, 0x9, 0xc00059dd38, 0x19b8d00, 0x8127d5)
	/usr/local/go/src/bufio/bufio.go:226 +0x24f
io.ReadAtLeast(0x1b3c340, 0xc00007b680, 0xc0005962d8, 0x9, 0x9, 0x9, 0xc00008c030, 0x0, 0x1b3c7a0)
	/usr/local/go/src/io/io.go:310 +0x87
io.ReadFull(...)
	/usr/local/go/src/io/io.go:329
net/http.http2readFrameHeader(0xc0005962d8, 0x9, 0x9, 0x1b3c340, 0xc00007b680, 0x0, 0x0, 0xc0008e8300, 0x0)
	/usr/local/go/src/net/http/h2_bundle.go:1479 +0x87
net/http.(*http2Framer).ReadFrame(0xc0005962a0, 0xc0008e8300, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/h2_bundle.go:1737 +0xa1
net/http.(*http2clientConnReadLoop).run(0xc00059dfa8, 0xc00056c380, 0x18)
	/usr/local/go/src/net/http/h2_bundle.go:8246 +0x8d
net/http.(*http2ClientConn).readLoop(0xc00024e900)
	/usr/local/go/src/net/http/h2_bundle.go:8174 +0x6f
created by net/http.(*http2Transport).newClientConn
	/usr/local/go/src/net/http/h2_bundle.go:7174 +0x64a

goroutine 53 [IO wait]:
internal/poll.runtime_pollWait(0x7ff0ca41ca08, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc00031d118, 0x72, 0xdd00, 0xddc7, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00031d100, 0xc000c78000, 0xddc7, 0xddc7, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc00031d100, 0xc000c78000, 0xddc7, 0xddc7, 0x203000, 0x4208a5, 0xc0007610a0)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0000b0c90, 0xc000c78000, 0xddc7, 0xddc7, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x8e
crypto/tls.(*atLeastReader).Read(0xc0007610a0, 0xc000c78000, 0xddc7, 0xddc7, 0x9dac, 0xc000c7c016, 0xc00059e9c8)
	/usr/local/go/src/crypto/tls/conn.go:760 +0x60
bytes.(*Buffer).ReadFrom(0xc000113758, 0x1b3c560, 0xc0007610a0, 0x40a375, 0x170af40, 0x1877580)
	/usr/local/go/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc000113500, 0x1b3e7e0, 0xc0000b0c90, 0x5, 0xc0000b0c90, 0xc00004c000)
	/usr/local/go/src/crypto/tls/conn.go:782 +0xec
crypto/tls.(*Conn).readRecordOrCCS(0xc000113500, 0x0, 0x0, 0xc00059ed38)
	/usr/local/go/src/crypto/tls/conn.go:589 +0x115
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:557
crypto/tls.(*Conn).Read(0xc000113500, 0xc0005be000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1233 +0x15b
bufio.(*Reader).Read(0xc0006669c0, 0xc0005963b8, 0x9, 0x9, 0xc00059ed38, 0x19b8d00, 0x8127d5)
	/usr/local/go/src/bufio/bufio.go:226 +0x24f
io.ReadAtLeast(0x1b3c340, 0xc0006669c0, 0xc0005963b8, 0x9, 0x9, 0x9, 0xc00008c030, 0x0, 0x1b3c7a0)
	/usr/local/go/src/io/io.go:310 +0x87
io.ReadFull(...)
	/usr/local/go/src/io/io.go:329
net/http.http2readFrameHeader(0xc0005963b8, 0x9, 0x9, 0x1b3c340, 0xc0006669c0, 0x0, 0x0, 0xc000124750, 0x0)
	/usr/local/go/src/net/http/h2_bundle.go:1479 +0x87
net/http.(*http2Framer).ReadFrame(0xc000596380, 0xc000124750, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/h2_bundle.go:1737 +0xa1
net/http.(*http2clientConnReadLoop).run(0xc00059efa8, 0x0, 0x0)
	/usr/local/go/src/net/http/h2_bundle.go:8246 +0x8d
net/http.(*http2ClientConn).readLoop(0xc00024f980)
	/usr/local/go/src/net/http/h2_bundle.go:8174 +0x6f
created by net/http.(*http2Transport).newClientConn
	/usr/local/go/src/net/http/h2_bundle.go:7174 +0x64a

goroutine 49 [IO wait]:
internal/poll.runtime_pollWait(0x7ff0ca41cd88, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc000261b98, 0x72, 0x1200, 0x12a3, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000261b80, 0xc000710000, 0x12a3, 0x12a3, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc000261b80, 0xc000710000, 0x12a3, 0x12a3, 0x203000, 0xc, 0xc000710005)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0000b0c78, 0xc000710000, 0x12a3, 0x12a3, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x8e
crypto/tls.(*atLeastReader).Read(0xc0006b82c0, 0xc000710000, 0x12a3, 0x12a3, 0x400, 0x7ff0ca5ad500, 0xc0004bb9c8)
	/usr/local/go/src/crypto/tls/conn.go:760 +0x60
bytes.(*Buffer).ReadFrom(0xc000112cd8, 0x1b3c560, 0xc0006b82c0, 0x40a375, 0x170af40, 0x1877580)
	/usr/local/go/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc000112a80, 0x1b3e7e0, 0xc0000b0c78, 0x5, 0xc0000b0c78, 0x8)
	/usr/local/go/src/crypto/tls/conn.go:782 +0xec
crypto/tls.(*Conn).readRecordOrCCS(0xc000112a80, 0x0, 0x0, 0xc0004bbd38)
	/usr/local/go/src/crypto/tls/conn.go:589 +0x115
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:557
crypto/tls.(*Conn).Read(0xc000112a80, 0xc000230000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1233 +0x15b
bufio.(*Reader).Read(0xc0004e1f20, 0xc0005961f8, 0x9, 0x9, 0xc0004bbd38, 0x19b8d00, 0x8127d5)
	/usr/local/go/src/bufio/bufio.go:226 +0x24f
io.ReadAtLeast(0x1b3c340, 0xc0004e1f20, 0xc0005961f8, 0x9, 0x9, 0x9, 0xc00008c030, 0x0, 0x1b3c7a0)
	/usr/local/go/src/io/io.go:310 +0x87
io.ReadFull(...)
	/usr/local/go/src/io/io.go:329
net/http.http2readFrameHeader(0xc0005961f8, 0x9, 0x9, 0x1b3c340, 0xc0004e1f20, 0x0, 0x0, 0xc000a7c5a0, 0x0)
	/usr/local/go/src/net/http/h2_bundle.go:1479 +0x87
net/http.(*http2Framer).ReadFrame(0xc0005961c0, 0xc000a7c5a0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/h2_bundle.go:1737 +0xa1
net/http.(*http2clientConnReadLoop).run(0xc0004bbfa8, 0xc00056c380, 0x18)
	/usr/local/go/src/net/http/h2_bundle.go:8246 +0x8d
net/http.(*http2ClientConn).readLoop(0xc00024e480)
	/usr/local/go/src/net/http/h2_bundle.go:8174 +0x6f
created by net/http.(*http2Transport).newClientConn
	/usr/local/go/src/net/http/h2_bundle.go:7174 +0x64a

goroutine 45 [IO wait]:
internal/poll.runtime_pollWait(0x7ff0ca41cae8, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc00031c598, 0x72, 0x10200, 0x10278, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00031c580, 0xc000798000, 0x10278, 0x10278, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc00031c580, 0xc000798000, 0x10278, 0x10278, 0x203000, 0xc, 0xc0007a0031)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0000b0c80, 0xc000798000, 0x10278, 0x10278, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x8e
crypto/tls.(*atLeastReader).Read(0xc000310e40, 0xc000798000, 0x10278, 0x10278, 0x8247, 0xc0007a002c, 0xc00059c9c8)
	/usr/local/go/src/crypto/tls/conn.go:760 +0x60
bytes.(*Buffer).ReadFrom(0xc000113058, 0x1b3c560, 0xc000310e40, 0x40a375, 0x170af40, 0x1877580)
	/usr/local/go/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc000112e00, 0x1b3e7e0, 0xc0000b0c80, 0x5, 0xc0000b0c80, 0xc0007a0031)
	/usr/local/go/src/crypto/tls/conn.go:782 +0xec
crypto/tls.(*Conn).readRecordOrCCS(0xc000112e00, 0x0, 0x0, 0xc00059cd38)
	/usr/local/go/src/crypto/tls/conn.go:589 +0x115
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:557
crypto/tls.(*Conn).Read(0xc000112e00, 0xc00070b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1233 +0x15b
bufio.(*Reader).Read(0xc00025d0e0, 0xc00070c038, 0x9, 0x9, 0xc00059cd38, 0x19b8d00, 0x8127d5)
	/usr/local/go/src/bufio/bufio.go:226 +0x24f
io.ReadAtLeast(0x1b3c340, 0xc00025d0e0, 0xc00070c038, 0x9, 0x9, 0x9, 0xc00008c030, 0x0, 0x1b3c7a0)
	/usr/local/go/src/io/io.go:310 +0x87
io.ReadFull(...)
	/usr/local/go/src/io/io.go:329
net/http.http2readFrameHeader(0xc00070c038, 0x9, 0x9, 0x1b3c340, 0xc00025d0e0, 0x0, 0x0, 0xc00055e870, 0x0)
	/usr/local/go/src/net/http/h2_bundle.go:1479 +0x87
net/http.(*http2Framer).ReadFrame(0xc00070c000, 0xc00055e870, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/h2_bundle.go:1737 +0xa1
net/http.(*http2clientConnReadLoop).run(0xc00059cfa8, 0x0, 0x0)
	/usr/local/go/src/net/http/h2_bundle.go:8246 +0x8d
net/http.(*http2ClientConn).readLoop(0xc00039a900)
	/usr/local/go/src/net/http/h2_bundle.go:8174 +0x6f
created by net/http.(*http2Transport).newClientConn
	/usr/local/go/src/net/http/h2_bundle.go:7174 +0x64a
```

**Output of `helm version`:**

```shell
ubuntu@vpn1:~/DevOps$ helm version
Client: &version.Version{SemVer:"v2.16.12", GitCommit:"47f0b88409e71fd9ca272abc7cd762a56a1c613e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.12", GitCommit:"47f0b88409e71fd9ca272abc7cd762a56a1c613e", GitTreeState:"clean"}
```

**Output of `kubectl version`:**

```shell
ubuntu@vpn1:~/DevOps$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:40:09Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-d88609", GitCommit:"d886092805d5cc3a47ed5cf0c43de38ce442dfcb", GitTreeState:"clean", BuildDate:"2021-07-31T00:29:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Cloud Provider/Platform (AKS, GKE, Minikube etc.):** AWS EKS

**Comment by bacongobbler** [comment]
Helm 2's support lifecycle ended on November 2020. See [the blog post](https://helm.sh/blog/helm-2-becomes-unsupported/) for more details. Because of this we are no longer providing support. Thanks.
