### ISSUE TITLE
Nil Pointer Error from `helm list`

### ISSUE THREAD

**Issue by rwxrob** [helm/helm#10352]
Output of `helm version`:

(blows up as below, but when restored is the following)

```
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Unable to connect to the server: dial tcp 192.168.58.2:8443: connect: no route to host
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

*didn't get that far*

## Problem

The following nil pointer segfault is thrown when adding a plugin that
contains an empty `plugin.yaml` file.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1780b21]

goroutine 1 [running]:
helm.sh/helm/v3/pkg/plugin.validatePluginData(0xc00059a640, 0xc0000449c0, 0x38, 0x190f120, 0xc00059a640)
	/home/circleci/helm.sh/helm/pkg/plugin/plugin.go:176 +0x41
helm.sh/helm/v3/pkg/plugin.LoadDir(0xc000044980, 0x2c, 0xc000044980, 0x2c, 0x1)
	/home/circleci/helm.sh/helm/pkg/plugin/plugin.go:228 +0x2f4
helm.sh/helm/v3/pkg/plugin.LoadAll(0xc0005ae210, 0x26, 0x1c0e93d, 0x1, 0x0, 0x0, 0xc0001be4a0)
	/home/circleci/helm.sh/helm/pkg/plugin/plugin.go:249 +0x196
helm.sh/helm/v3/pkg/plugin.FindPlugins(0xc0005ae210, 0x26, 0x0, 0x0, 0x1, 0xffffffffffffffff, 0x5)
	/home/circleci/helm.sh/helm/pkg/plugin/plugin.go:263 +0xc5
main.loadPlugins(0xc0005a42c0, 0x1e4fce0, 0xc00013c008)
	/home/circleci/helm.sh/helm/cmd/helm/load_plugins.go:60 +0x85
main.newRootCmd(0xc000053d40, 0x1e4fce0, 0xc00013c008, 0xc00012e030, 0x1, 0x1, 0x1887f11, 0xc000154000, 0x1d05c10)
	/home/circleci/helm.sh/helm/cmd/helm/root.go:207 +0xa85
main.main()
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:63 +0xb6
```

**Comment by yxxhero** [comment]
duplicate https://github.com/helm/helm/issues/9912

**Comment by yxxhero** [comment]
> duplicate #9912

sorry. Are caused by different reasons.

**Comment by zonggen** [comment]
Seems like null pointer dereference in https://github.com/helm/helm/blob/dd0177aed71dd3c5b044e25c55870cd66f0f05fa/pkg/plugin/plugin.go#L176 caused by default 0 value for pointers https://github.com/helm/helm/blob/dd0177aed71dd3c5b044e25c55870cd66f0f05fa/pkg/plugin/plugin.go#L111. Could use the actual struct instead of pointer to give it valid default 0 value, but there might be side effects which I'm not sure of.

**Comment by zetHannes** [comment]
I've created a PR #10728 for this issue which prevents the Nil Pointer error to be thrown.
