### ISSUE TITLE
helm package --dependency-update with OCI dependencies is broken

### ISSUE THREAD

**Issue by tompizmor** [helm/helm#10608]
With new Helm 3.8.0 release, the `helm package --dependency-update` is broken if the chart to package contains OCI dependencies.

This is the error I get:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x539b42b]

goroutine 1 [running]:
helm.sh/helm/v3/pkg/registry.(*Client).Tags(0x0, {0xc0012fa780, 0xc000bc1b78})
	helm.sh/helm/v3/pkg/registry/client.go:581 +0x12b
helm.sh/helm/v3/internal/resolver.(*Resolver).Resolve(0xc000bc1bf0, {0xc0001c8640, 0x3, 0x4}, 0x1)
	helm.sh/helm/v3/internal/resolver/resolver.go:140 +0x57d
helm.sh/helm/v3/pkg/downloader.(*Manager).resolve(0xc000984750, {0xc0001c8640, 0xc0001c8640, 0x3}, 0xc000984750)
	helm.sh/helm/v3/pkg/downloader/manager.go:236 +0x70
helm.sh/helm/v3/pkg/downloader.(*Manager).Update(0xc000984750)
	helm.sh/helm/v3/pkg/downloader/manager.go:195 +0xe5
main.newPackageCmd.func1(0xc000459180, {0xc0004e04c0, 0x1, 0x4})
	helm.sh/helm/v3/cmd/helm/package.go:99 +0x5f6
github.com/spf13/cobra.(*Command).execute(0xc000459180, {0xc0004e0480, 0x4, 0x4})
	github.com/spf13/cobra@v1.3.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001aea00)
	github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.3.0/command.go:902
main.main()
	helm.sh/helm/v3/cmd/helm/helm.go:83 +0x234
```

I've been checking the code and it seems the problem is that no RegistryClient is set when creating the downloader.Manager.

I will try to send a PR with a fix

**Comment by mattfarina** [comment]
This should be fixed with the merger of https://github.com/helm/helm/pull/10609
