### ISSUE TITLE
go panic on invalid value locations

### ISSUE THREAD

**Issue by jkroepke** [helm/helm#10685]
If I define a invalid non local value fine, helm raises a go panic.

```
helm template examples -f "http://a.b"           
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x54b7018]

goroutine 1 [running]:
bytes.(*Buffer).Bytes(...)
        bytes/buffer.go:54
helm.sh/helm/v3/pkg/cli/values.readFile({0xc000391170, 0x100000000000007}, {0xc0005bf380, 0x4, 0x4})
        helm.sh/helm/v3/pkg/cli/values/options.go:120 +0x138
helm.sh/helm/v3/pkg/cli/values.(*Options).MergeValues(0xc0003f7f80, {0xc0005bf380, 0xc00085f9f8, 0xc000787880})
        helm.sh/helm/v3/pkg/cli/values/options.go:48 +0x385
main.runInstall({0xc000432420, 0x40ad826, 0xc00085fa88}, 0xc0004be6e0, 0xc000516810, {0x5c42ce0, 0xc0001a6008})
        helm.sh/helm/v3/cmd/helm/install.go:198 +0x385
main.newTemplateCmd.func2(0xc000156c80, {0xc000432420, 0x3, 0x3})
        helm.sh/helm/v3/cmd/helm/template.go:82 +0x22a
github.com/spf13/cobra.(*Command).execute(0xc000156c80, {0xc0004323f0, 0x3, 0x3})
        github.com/spf13/cobra@v1.3.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc00016ca00)
        github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.3.0/command.go:902
main.main()
        helm.sh/helm/v3/cmd/helm/helm.go:83 +0x234

```

Output of `helm version`:
```
helm version
version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.6"}
```

**Comment by joejulian** [comment]
Unfortunately, I'm unable to duplicate that. Is there anything that might be unique to your environment that might have an impact?

```
$  helm template examples-f "http://a.b"
Error: failed to download "http://a.b"
```

**Comment by jkroepke** [comment]
Sorry. I was missing a space here.

```
jkr@joe-nb helm-secrets % helm template examples-f "http://a.b" 
Error: failed to download "http://a.b"
jkr@joe-nb helm-secrets % helm template examples -f "http://a.b"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x54b7018]

goroutine 1 [running]:
bytes.(*Buffer).Bytes(...)
        bytes/buffer.go:54
helm.sh/helm/v3/pkg/cli/values.readFile({0xc0007206d0, 0x100000000000007}, {0xc000718c80, 0x4, 0x4})
        helm.sh/helm/v3/pkg/cli/values/options.go:120 +0x138
helm.sh/helm/v3/pkg/cli/values.(*Options).MergeValues(0xc000342c00, {0xc000718c80, 0xc0008f59f8, 0xc000469c40})
        helm.sh/helm/v3/pkg/cli/values/options.go:48 +0x385
main.runInstall({0xc000728b40, 0x1, 0xc0008f5ac0}, 0xc00019bce0, 0x2000, {0x5c42ce0, 0xc000010018})
        helm.sh/helm/v3/cmd/helm/install.go:198 +0x385
main.newTemplateCmd.func2(0xc000488a00, {0xc000728b40, 0x3, 0x3})
        helm.sh/helm/v3/cmd/helm/template.go:82 +0x22a
github.com/spf13/cobra.(*Command).execute(0xc000488a00, {0xc000728b10, 0x3, 0x3})
        github.com/spf13/cobra@v1.3.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0005a8780)
        github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.3.0/command.go:902
main.main()
        helm.sh/helm/v3/cmd/helm/helm.go:83 +0x234

```

**Comment by joejulian** [comment]
Still no joy for me:
```
 helm template examples -f "http://a.b"

Error: failed to download "examples"
```

**Comment by joejulian** [comment]
Heh... I realized my mistake.

Full repro:

```
helm create examples
helm template examples -f "http://a.b"
```

**Comment by yxxhero** [comment]
@joejulian Are you interested in solving this issue?

**Comment by yxxhero** [comment]
@jkroepke and you? Are you interested in solving this issue? Thanks very much.

**Comment by joejulian** [comment]
It looks like what's happening is that this line 119 is returning an error. Instead of testing and returning that error, it was thought that it could be returned on 120 and that would satisfy the error check. 
https://github.com/helm/helm/blob/9bf3a14203099759713828aae8b880776e8ff261/pkg/cli/values/options.go#L119-L120
Unfortunately, the `Bytes()` method for the Buffer struct pointer errors because `data` is nil and you can't call `(*nil).Bytes()`.

I think testing and returning the error between those lines should be sufficient to fix that, but a test should also be added in options_test.go to prove it.

**Comment by jkroepke** [comment]
fixed in https://github.com/helm/helm/pull/10832

**Comment by Lohitsalavadhi** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11a505b]

goroutine 1 [running]:
main.main()
        /Users/lohits/Documents/header_testing/go_test/server.go:78 +0x4fb
exit status 2
