### ISSUE TITLE
 azure-kubernetes-service-helm.yml 

### ISSUE THREAD

**Issue by nguemechieu** [helm/helm#11467]
After a long trying and check over internet I'm unable to fix this issue .Please help me!
//Below are error message from GitHub action
Run azure/k8s-bake@v2.1
/usr/bin/unzip -o -q /home/runner/work/_temp/c58f4f02-bd3c-41e5-82b0-341281d63bf6
Running helm dependency update command..
/opt/hostedtoolcache/helm/3.10.1/x64/linux-amd64/helm dependency update ./tradeadviser/charts/chart.yaml
Error: only unpacked charts can be updated
Error: Error: Failed to run bake action. Error: Error: The process '/opt/hostedtoolcache/helm/3.10.1/x64/linux-amd64/helm' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/azure/k8s-bake/v2.1/node_modules/@actions/exec/lib/toolrunner.js:592:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/azure/k8s-bake/v2.1/node_modules/@actions/exec/lib/toolrunner.js:575:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/azure/k8s-bake/v2.1/node_modules/@actions/exec/lib/toolrunner.js:469:27)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
0s

**Comment by joejulian** [comment]
`helm dependency update ./tradeadviser/charts/chart.yaml` should probably be `helm dependency update ./tradeadviser/charts`. Also, `chart.yaml` should be `Chart.yaml`.

**Comment by nguemechieu** [comment]
Thanks for quick answer. This is what I found.
- On azure when using automated deployment,github action require to have the another Chart.yaml in the specify directory without replacing or removing the first file Chart.yaml that was created at init . 
- After Adding my Chart.yaml in the templates directory ,everything  started working.
- Here the final output
Run helm upgrade --wait -i -f ./tradeadviser/values.yaml  automated-deployment ./tradeadviser/templates
Release "automated-deployment" has been upgraded. Happy Helming!
NAME: automated-deployment
LAST DEPLOYED: Tue Oct 25 21:31:08 2022
NAMESPACE: default
STATUS: deployed
REVISION: 4
TEST SUITE: None
