### ISSUE TITLE
Synchrony pod results in error when installing atlassian-data-center/confluence.

### ISSUE THREAD

**Issue by sangamewin** [helm/helm#13381]
Synchrony pod does not start.  Always get the error on the log. Please see logs below. There is no additionalJvmArgs passed. Fact is that additionalJvmArgs property available at 2 location and at both places its "additionalJvmArgs "
Both properties are at below location.
confluence.additionalJvmArgs  and synchrony.resources.additionalJvmArgs 

same scripts were working 2 weeks before, but now not, there is not code change, only helm repo update

 helm install ver-8-5-4 atlassian-data-center/confluence --namespace conf-test --version 1.0.0 --values values.yaml
**coalesce.go:286: warning: cannot overwrite table with non table for confluence.synchrony.additionalJvmArgs (map[])**
W1008 12:57:04.272774    6412 warnings.go:70] annotation "kubernetes.io/ingress.class" is deprecated, please use 'spec.ingressClassName' instead
W1008 12:57:04.290416    6412 warnings.go:70] annotation "kubernetes.io/ingress.class" is deprecated, please use 'spec.ingressClassName' instead
NAME: ver-8-5-4
LAST DEPLOYED: Tue Oct  8 12:57:01 2024
NAMESPACE: conf-test
STATUS: deployed
REVISION: 1
NOTES:
Thank you for installing Confluence.

 kubectl get pods
NAME                               READY   STATUS             RESTARTS      AGE
ver-8-5-4-confluence-0             1/1     Running            0             23m
**ver-8-5-4-confluence-synchrony-0   0/1     CrashLoopBackOff   9 (98s ago)   23m**

 kubectl logs -f ver-8-5-4-confluence-synchrony-0
Loading synchrony
WARNING: update-vals already refers to: #'clojure.core/update-vals in namespace: clojure.tools.analyzer.utils, being replaced by: #'clojure.tools.analyzer.utils/update-vals
WARNING: update-keys already refers to: #'clojure.core/update-keys in namespace: clojure.tools.analyzer.utils, being replaced by: #'clojure.tools.analyzer.utils/update-keys
WARNING: update-vals already refers to: #'clojure.core/update-vals in namespace: clojure.tools.analyzer, being replaced by: #'clojure.tools.analyzer.utils/update-vals
WARNING: update-keys already refers to: #'clojure.core/update-keys in namespace: clojure.tools.analyzer, being replaced by: #'clojure.tools.analyzer.utils/update-keys
WARNING: update-vals already refers to: #'clojure.core/update-vals in namespace: clojure.tools.analyzer.passes, being replaced by: #'clojure.tools.analyzer.utils/update-vals
WARNING: update-vals already refers to: #'clojure.core/update-vals in namespace: clojure.tools.analyzer.passes.uniquify, being replaced by: #'clojure.tools.analyzer.utils/update-vals
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/atlassian/confluence/confluence/WEB-INF/packages/synchrony-standalone.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/atlassian/confluence/confluence/WEB-INF/lib/org.apache.logging.log4j_log4j-slf4j-impl-2.19.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Reload4jLoggerFactory]
WARNING: abs already refers to: #'clojure.core/abs in namespace: medley.core, being replaced by: #'medley.core/abs
Starting synchrony
Exception in thread "main" clojure.lang.ExceptionInfo: error while starting state #'synchrony.config/config {:var #'synchrony.config/config}
        at mount.lite$start$fn__24131.invoke(lite.clj:153)
        at mount.lite$start.invokeStatic(lite.clj:150)
        at mount.lite$start.invoke(lite.clj:136)
        at mount.lite$start.invokeStatic(lite.clj:141)
        at mount.lite$start.invoke(lite.clj:136)
        at synchrony.core$start_BANG_.invokeStatic(core.clj:21)
        at synchrony.core$start_BANG_.invoke(core.clj:21)
        at synchrony.core$_main.invokeStatic(core.clj:42)
        at synchrony.core$_main.doInvoke(core.clj:40)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at synchrony.core.main(Unknown Source)
Caused by: java.net.MalformedURLException: no protocol:
        at java.base/java.net.URL.<init>(URL.java:645)
        at java.base/java.net.URL.<init>(URL.java:541)
        at java.base/java.net.URL.<init>(URL.java:488)
        at clojure.java.io$fn__11505.invokeStatic(io.clj:44)
        at clojure.java.io$fn__11505.invoke(io.clj:44)
        at clojure.java.io$fn__11476$G__11471__11481.invoke(io.clj:35)
        at synchrony.config$load_config.invokeStatic(config.clj:70)
        at synchrony.config$load_config.invoke(config.clj:63)
        at synchrony.config$config_start_BANG_.invokeStatic(config.clj:138)
        at synchrony.config$config_start_BANG_.invoke(config.clj:138)
        at synchrony.config$fn__24182$fn__24185.invoke(config.clj:140)
        at mount.lite.State.start_STAR_(lite.clj:44)
        at mount.lite$start$fn__24131.invoke(lite.clj:151)
        ... 10 more

Output of `helm version`:  version.BuildInfo{Version:"v3.14.4", GitCommit:"81c902a123462fd4052bc5e9aa9c513c4c8fc142", GitTreeState:"clean", GoVersion:"go1.21.9"}

Output of `kubectl version`:
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.13

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AKS

**Comment by yxxhero** [comment]
@sangamewin this is not helm issue. maybe you should post a issue in atlassian-data-center/confluence repo.
