### ISSUE TITLE
helm update

### ISSUE THREAD

**Issue by rimusz** [helm/helm#317]
helm update spits errors
```
helm --debug update
---> Checking repo charts
[ERROR] Not all repos could be updated: exit status 1
panic: Not all repos could be updated: exit status 1

goroutine 1 [running]:
github.com/helm/helm/log.Die(0x8a5fc0, 0x22, 0xc8200c4f20, 0x1, 0x1)
	/home/travis/gopath/src/github.com/helm/helm/log/log.go:46 +0xe1
github.com/helm/helm/action.Update(0xc82042a520, 0x1f)
	/home/travis/gopath/src/github.com/helm/helm/action/update.go:23 +0x30f
main.main.func3(0xc8201990e0)
	/home/travis/gopath/src/github.com/helm/helm/helm.go:95 +0x90
github.com/helm/helm/vendor/github.com/codegangsta/cli.Command.Run(0x8034c8, 0x6, 0x0, 0x0, 0xc8201ab4f0, 0x1, 0x1, 0x8df4c0, 0x31, 0x97ace0, ...)
	/home/travis/gopath/src/github.com/helm/helm/vendor/github.com/codegangsta/cli/command.go:131 +0x1055
github.com/helm/helm/vendor/github.com/codegangsta/cli.(*App).Run(0xc820198ea0, 0xc82000a2d0, 0x3, 0x3, 0xee8028, 0xc82043b760)
	/home/travis/gopath/src/github.com/helm/helm/vendor/github.com/codegangsta/cli/app.go:175 +0xfd6
github.com/helm/helm/vendor/github.com/codegangsta/cli.(*App).RunAndExitOnError(0xc820198ea0)
	/home/travis/gopath/src/github.com/helm/helm/vendor/github.com/codegangsta/cli/app.go:186 +0x54
main.main()
	/home/travis/gopath/src/github.com/helm/helm/helm.go:365 +0x1b8b

goroutine 5 [chan receive]:
github.com/helm/helm/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0xbe0c20)
	/home/travis/gopath/src/github.com/helm/helm/vendor/github.com/golang/glog/glog.go:879 +0x67
created by github.com/helm/helm/vendor/github.com/golang/glog.init.1
	/home/travis/gopath/src/github.com/helm/helm/vendor/github.com/golang/glog/glog.go:410 +0x297
```

**Comment by technosophos** [comment]
One of your `cache/` repos is probably not right. That particular error comes when the Git operation is not able to update one of the repos inside of `cache/`.

If you recently updated from 0.1 to 0.2, you might have to go through the steps in the README to re-set your charts repo.

**Comment by rimusz** [comment]
my bad, did not see that re-set step.

**Comment by technosophos** [comment]
No worries. It indicates to me that I did it wrong. I should have documented it better (or made the process seamless). It should definitely not have been tripping people up.

**Comment by rimusz** [comment]
lets have the proper upgrade from v0.2 to v0.3 then :)
