### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by danielcb** [helm/helm#3625]
Kubernetes:
```
GKE Kubernetes 1.9.3-gke.0
```

Helm:
```
Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
```

We're trying to mass deploy a few dummy services via helm/tiller and regularly get the following panic (every ~100 deployments or so):

```
/go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:573 +0xa1
created by k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
/go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:572 +0xa9
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420ce9c00, 0xc420299e00, 0x2981120, 0xc42070d760, 0xc420ec0300)
/go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:1023 +0x15a6
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).handleStream(0xc420299e00, 0x2981120, 0xc42070d760, 0xc420ec0300, 0x0)
/go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:826 +0xc41
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc420299e00, 0x2981120, 0xc42070d760, 0xc420ec0300, 0xc420248420, 0x29eb8c8, 0x0, 0x0, 0x0)
/go/src/k8s.io/helm/pkg/proto/hapi/services/tiller.pb.go:1230 +0x177
k8s.io/helm/pkg/proto/hapi/services._ReleaseService_InstallRelease_Handler(0x1c03f40, 0xc420248060, 0x7f051140c000, 0xc420ed38c0, 0xc420e68eb0, 0x1cf4608, 0x0, 0x0, 0x43310e, 0xc4208c0d00)
/go/src/k8s.io/helm/pkg/tiller/server.go:60 +0xb5
k8s.io/helm/pkg/tiller.newUnaryInterceptor.func1(0x7f051140c000, 0xc420ed38c0, 0x1b8ad00, 0xc4209c0de0, 0xc4209bdbe0, 0xc4209bdc00, 0x0, 0xc420ce59d8, 0x40fe28, 0x50)
/go/src/k8s.io/helm/vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server_metrics.go:86 +0xdb
k8s.io/helm/vendor/github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x7f051140c000, 0xc420ed38c0, 0x1b8ad00, 0xc4209c0de0, 0xc4209bdbe0, 0xc4209bdc00, 0xc420299e70, 0xc4209bda20, 0xc420ce5960, 0x40fe28)
/go/src/k8s.io/helm/pkg/proto/hapi/services/tiller.pb.go:1228 +0x86
k8s.io/helm/pkg/proto/hapi/services._ReleaseService_InstallRelease_Handler.func1(0x7f051140c000, 0xc420ed38c0, 0x1b8ad00, 0xc4209c0de0, 0x33, 0xc420e690e0, 0x83b701, 0x2a1fd50)
/go/src/k8s.io/helm/pkg/tiller/release_install.go:36 +0xff
k8s.io/helm/pkg/tiller.(*ReleaseServer).InstallRelease(0xc420248060, 0x7f051140c000, 0xc420ed38c0, 0xc4209c0de0, 0xc420248060, 0x1c9d07f, 0xe)
/go/src/k8s.io/helm/pkg/tiller/release_install.go:63 +0x71
k8s.io/helm/pkg/tiller.(*ReleaseServer).prepareRelease(0xc420248060, 0xc4209c0de0, 0xc420ce9e50, 0x1, 0x1)
/go/src/k8s.io/helm/pkg/tiller/release_server.go:190 +0x644
k8s.io/helm/pkg/tiller.(*ReleaseServer).uniqName(0xc420248060, 0x0, 0x0, 0x20ce5600, 0xc420ce5698, 0x602a60, 0xc42077a050, 0xc42037fb00)
goroutine 2633 [running]:

[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x17388d4]
panic: runtime error: invalid memory address or nil pointer dereference
```

The chart itself is a simple whoami deployment with network policies, each in it's own namespace and deployed via a for loop:
```
for i in $(seq 1 1000); do helm install --namespace=test-$i ./test-chart > /dev/null; done
```

**Comment by dove-young** [comment]
I hit the same problem at `helm search` command, if I gave repo name in UPPERCASE in `helm repo add ` command. 

I hit this problem with `helm` client v2.7.2 and v2.8.0. 

```
linux-amd64/helm search apm --debug
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16e41c3]

goroutine 1 [running]:
main.(*searchCmd).formatSearchResults(0xc42063ec00, 0xc42177ec40, 0x2, 0x2, 0xc42177ec40, 0x2)
	/go/src/k8s.io/helm/cmd/helm/search.go:137 +0x2e3
main.(*searchCmd).run(0xc42063ec00, 0xc4201f3620, 0x1, 0x2, 0x0, 0x0)
	/go/src/k8s.io/helm/cmd/helm/search.go:96 +0x135
main.newSearchCmd.func1(0xc420286b40, 0xc4201f3620, 0x1, 0x2, 0x0, 0x0)
	/go/src/k8s.io/helm/cmd/helm/search.go:61 +0x75
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).execute(0xc420286b40, 0xc4201f3460, 0x2, 0x2, 0xc420286b40, 0xc4201f3460)
	/go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:599 +0x3e9
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420401200, 0xc4203bb680, 0xc4203bbd40, 0xc4203b0480)
	/go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:689 +0x339
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420401200, 0x3, 0x3)
	/go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
	/go/src/k8s.io/helm/cmd/helm/helm.go:159 +0x77
```

**Comment by bacongobbler** [comment]
@dove-young FYI that was fixed in v2.8.2 via #3615, though that's unrelated to OP's issue I think :)

**Comment by frankh** [comment]
I'm having the same problem when trying to delete a release that uses rabbitmq as a dependency

In the tiller logs i get:

```
[kube] 2018/05/04 10:12:50 Starting delete for "affable-condor-rabbitmq" StatefulSet
panic: runtime error: invalid memory address or nil pointer dereference
k8s.io/helm/vendor/k8s.io/kubernetes/pkg/kubectl.ReaperFor(0xc420808880, 0x4, 0xc4208088d0, 0xb, 0x0, 0x0, 0x1ea97c0, 0xc420911360, 0x0, 0xc420201860)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/k8s.io/kubernetes/pkg/kubectl/stop.go:92 +0xe39
k8s.io/helm/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/util.(*ring1Factory).Reaper(0xc420319e70, 0xc42043c770, 0xc4206fe940, 0xc420911438, 0x5f4e4e, 0xc4206fe910)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/util/factory_object_mapping.go:290 +0x160
k8s.io/helm/vendor/k8s.io/kubernetes/pkg/kubect
....etc (can post full traceback if needed)
```

**Comment by gintautassulskus** [comment]
The same issue occurs with 1.10.0-rc.1 attempting to run `helm list`.


```
Client: &version.Version{SemVer:"v2.10.0-rc.1", GitCommit:"aa98e7e3dd2356bce72e8e367e8c87e8085c692b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0-rc.1", GitCommit:"aa98e7e3dd2356bce72e8e367e8c87e8085c692b", GitTreeState:"clean"}
```


```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1e7ceb6]

goroutine 1 [running]:
main.(*listCmd).run(0xc420480990, 0xc42090a000, 0x1f97da0)
	/Users/user/go/src/k8s.io/helm/cmd/helm/list.go:170 +0x266
main.newListCmd.func2(0xc42079b8c0, 0x2ce8da8, 0x0, 0x0, 0x0, 0x0)
	/Users/user/go/src/k8s.io/helm/cmd/helm/list.go:117 +0x46
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).execute(0xc42079b8c0, 0x2ce8da8, 0x0, 0x0, 0xc42079b8c0, 0x2ce8da8)
	/Users/user/go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:599 +0x3db
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420808240, 0xc4207618c0, 0xc420758480, 0xc420758b40)
	/Users/user/go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:689 +0x2d4
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420808240, 0x1, 0x1)
	/Users/user/go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
	/Users/user/go/src/k8s.io/helm/cmd/helm/helm.go:160 +0x75
```

**Comment by bacongobbler** [comment]
That particular but was fixed in https://github.com/kubernetes/helm/pull/4325
 We'll be cherry picking that into the release. :)

**Comment by nonspecialist** [comment]
This appears to be because `uniqName` expects an actual error type to be returned from `s.env.Releases.Get()` -- and it often isn't. For example, if the storage driver is `cfgmaps` (the default), https://github.com/helm/helm/blob/b4b693c3168421c8cd7165e2fb5eb2233adefa6a/pkg/storage/driver/cfgmaps.go#L82 returns `err` as a `nil`, and `err.Error()` goes pop.

I've submitted PR #4627 to address this

**Comment by PeterGrace** [comment]
Not sure if this issue should be used for all instances of this sigsegv, but, I just ran across this while trying to upgrade a deployment.  In this upgrade, I'm creating a new secret, a new configmap, and altering the deployment to have a sidecar container.
```
kube-system tiller-deploy-67d8b477f7-wlvg7 tiller panic: runtime error: invalid memory address or nil pointer dereference
kube-system tiller-deploy-67d8b477f7-wlvg7 tiller [signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x12e7028]
kube-system tiller-deploy-67d8b477f7-wlvg7 tiller
kube-system tiller-deploy-67d8b477f7-wlvg7 tiller goroutine 65 [running]:
kube-system tiller-deploy-67d8b477f7-wlvg7 tiller k8s.io/helm/pkg/tiller.(*ReleaseServer).performUpdateForce(0xc4206f20f0, 0xc4200aaaa0, 0x0, 0x0, 0x17b50a0)
kube-system tiller-deploy-67d8b477f7-wlvg7 tiller       /go/src/k8s.io/helm/pkg/tiller/release_update.go:166 +0x188
kube-system tiller-deploy-67d8b477f7-wlvg7 tiller k8s.io/helm/pkg/tiller.(*ReleaseServer).UpdateRelease(0xc4206f20f0, 0x17d5e00, 0xc4206f2630, 0xc4200aaaa0, 0xc4206f20f0, 0x16b70a5, 0xd)
kube-system tiller-deploy-67d8b477f7-wlvg7 tiller       /go/src/k8s.io/helm/pkg/tiller/release_update.go:43 +0x245
kube-system tiller-deploy-67d8b477f7-wlvg7 tiller k8s.io/helm/pkg/proto/hapi/services._ReleaseService_UpdateRelease_Handler.func1(0x17d5e00, 0xc4206f2630, 0x1603f20, 0xc4200aaaa0, 0x32, 0xc4200ab450, 0xc4200aaa01, 0x0)
kube-system tiller-deploy-67d8b477f7-wlvg7 tiller       /go/src/k8s.io/helm/pkg/proto/hapi/services/tiller.pb.go:1244 +0x86
kube-system tiller-deploy-67d8b477f7-wlvg7 tiller k8s.io/helm/vendor/github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x17d5e00, 0xc4206f2630, 0x1603f20, 0xc4200aaaa0, 0xc42089a620, 0xc42089a640, 0x48, 0xc42089a5a0, 0xc42064ba40, 0x4108c8)
kube-system tiller-deploy-67d8b477f7-wlvg7 tiller       /go/src/k8s.io/helm/vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server_metrics.go:86 +0xdb
kube-system tiller-deploy-67d8b477f7-wlvg7 tiller k8s.io/helm/pkg/tiller.newUnaryInterceptor.func1(0x17d5e00, 0xc4206f2630, 0x1603f20, 0xc4200aaaa0, 0xc42089a620, 0xc42089a640, 0xc420753ab0, 0x4108c8, 0x50, 0x15d6360)
kube-system tiller-deploy-67d8b477f7-wlvg7 tiller       /go/src/k8s.io/helm/pkg/tiller/server.go:60 +0xab
kube-system tiller-deploy-67d8b477f7-wlvg7 tiller k8s.io/helm/pkg/proto/hapi/services._ReleaseService_UpdateRelease_Handler(0x163dd60, 0xc4206f20f0, 0x17d5e00, 0xc4206f2630, 0xc4200aa550, 0x1712cd8, 0x0, 0x0, 0xc42005c400, 0xc4200ad080)
kube-system tiller-deploy-67d8b477f7-wlvg7 tiller       /go/src/k8s.io/helm/pkg/proto/hapi/services/tiller.pb.go:1246 +0x167
kube-system tiller-deploy-67d8b477f7-wlvg7 tiller k8s.io/helm/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4200e9540, 0x17de900, 0xc420369e40, 0xc420892100, 0xc4206f2180, 0x215fcf0, 0x0, 0x0, 0x0)
kube-system tiller-deploy-67d8b477f7-wlvg7 tiller       /go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:826 +0x9c8
kube-system tiller-deploy-67d8b477f7-wlvg7 tiller k8s.io/helm/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4200e9540, 0x17de900, 0xc420369e40, 0xc420892100, 0x0)
kube-system tiller-deploy-67d8b477f7-wlvg7 tiller       /go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:1023 +0x1318
kube-system tiller-deploy-67d8b477f7-wlvg7 tiller k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4207405e0, 0xc4200e9540, 0x17de900, 0xc420369e40, 0xc420892100)
kube-system tiller-deploy-67d8b477f7-wlvg7 tiller       /go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:572 +0x9f
kube-system tiller-deploy-67d8b477f7-wlvg7 tiller created by k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
kube-system tiller-deploy-67d8b477f7-wlvg7 tiller       /go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:570 +0xa1
```

**Comment by bacongobbler** [comment]
closing as inactive.
