### ISSUE TITLE
Invalid --values argument results in segfault

### ISSUE THREAD

**Issue by mparry** [helm/helm#3679]
For example, if you accidentally specify `--values` when you meant `--set` - which was what I did - then you get this rather unfriendly result:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2139add]

goroutine 1 [running]:
main.readFile(0x7ffeefbff059, 0x2f, 0x7ffeefbff059, 0x2f, 0xc4200d01d8, 0x0, 0x0)
	/Users/m.parry/code/gocode/src/k8s.io/helm/cmd/helm/install.go:498 +0x8d
main.vals(0xc4204ae480, 0x5, 0x8, 0x34125f0, 0x0, 0x0, 0x2, 0xc420842600, 0x0, 0x23, ...)
	/Users/m.parry/code/gocode/src/k8s.io/helm/cmd/helm/install.go:337 +0x13a
main.(*installCmd).run(0xc4201f6000, 0x0, 0x27fe8c0)
	/Users/m.parry/code/gocode/src/k8s.io/helm/cmd/helm/install.go:210 +0x10e
...
```

**Comment by bacongobbler** [comment]
closing as inactive.
