### ISSUE TITLE
Panic when piping `helm help`

### ISSUE THREAD

**Issue by mboersma** [helm/helm#387]
The `helm` client errors in this case with "broken pipe." Other `helm` commands don't seem to have this problem.
```go
$ helm help | head -5
NAME:
   helm - The Kubernetes package manager

To begin working with Helm, run the 'helm update' command:

panic: template: help:15:30: executing "help" at <
GLOBAL OPTIONS:
   >: write /dev/stdout: broken pipe

goroutine 1 [running]:
github.com/helm/helm/vendor/github.com/codegangsta/cli.printHelp(0xe5d1e8, 0xc82002c010, 0x9e5b60, 0x23d, 0x7e4e40, 0xc8201a0d80)
	/Users/matt/Projects/src/github.com/helm/helm/vendor/github.com/codegangsta/cli/help.go:183 +0x40a
github.com/helm/helm/vendor/github.com/codegangsta/cli.ShowAppHelp(0xc8201a0fc0)
	/Users/matt/Projects/src/github.com/helm/helm/vendor/github.com/codegangsta/cli/help.go:110 +0x7b
github.com/helm/helm/vendor/github.com/codegangsta/cli.glob.func1(0xc8201a0fc0)
	/Users/matt/Projects/src/github.com/helm/helm/vendor/github.com/codegangsta/cli/help.go:81 +0x161
github.com/helm/helm/vendor/github.com/codegangsta/cli.Command.Run(0x8576d8, 0x4, 0x0, 0x0, 0xc629a0, 0x1, 0x1, 0x942be0, 0x30, 0x0, ...)
	/Users/matt/Projects/src/github.com/helm/helm/vendor/github.com/codegangsta/cli/command.go:131 +0x1055
github.com/helm/helm/vendor/github.com/codegangsta/cli.(*App).Run(0xc8201a0d80, 0xc82000a240, 0x2, 0x2, 0x0, 0x0)
	/Users/matt/Projects/src/github.com/helm/helm/vendor/github.com/codegangsta/cli/app.go:175 +0xfd6
github.com/helm/helm/vendor/github.com/codegangsta/cli.(*App).RunAndExitOnError(0xc8201a0d80)
	/Users/matt/Projects/src/github.com/helm/helm/vendor/github.com/codegangsta/cli/app.go:186 +0x54
main.main()
	/Users/matt/Projects/src/github.com/helm/helm/helm.go:6 +0x25

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/asm_amd64.s:1721 +0x1

goroutine 5 [chan receive]:
github.com/helm/helm/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0xc72aa0)
	/Users/matt/Projects/src/github.com/helm/helm/vendor/github.com/golang/glog/glog.go:879 +0x67
created by github.com/helm/helm/vendor/github.com/golang/glog.init.1
	/Users/matt/Projects/src/github.com/helm/helm/vendor/github.com/golang/glog/glog.go:410 +0x297
```

**Comment by technosophos** [comment]
This might be an upstream bug with codegangsta cli. If it is, we should probably file upstream.

**Comment by technosophos** [comment]
In fact, here it is:

https://github.com/codegangsta/cli/blob/cffab77ecb4f963ced9e30344eb2b9282ef36887/help.go#L182-L184

**Comment by technosophos** [comment]
I guess the next time we `glide up` this will be resolved.
