### ISSUE TITLE
helm list <release> causes nil pointer reference if release does not exist in 2.10.0-rc1

### ISSUE THREAD

**Issue by sudermanjr** [helm/helm#4408]
```
✓± helm list foo
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1e767d6]

goroutine 1 [running]:
main.(*listCmd).run(0xc42043cfc0, 0xc420a3e600, 0x1)
        /go/src/k8s.io/helm/cmd/helm/list.go:170 +0x266
main.newListCmd.func2(0xc420793d40, 0xc420508630, 0x1, 0x1, 0x0, 0x0)
        /go/src/k8s.io/helm/cmd/helm/list.go:117 +0x46
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).execute(0xc420793d40, 0xc420508600, 0x1, 0x1, 0xc420793d40, 0xc420508600)
        /go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:599 +0x3db
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4207d6000, 0xc420756000, 0xc420756900, 0xc420757200)
        /go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:689 +0x2d4
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4207d6000, 0x2, 0x2)
        /go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
        /go/src/k8s.io/helm/cmd/helm/helm.go:160 +0x75
```

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.10.0-rc.1", GitCommit:"aa98e7e3dd2356bce72e8e367e8c87e8085c692b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0-rc.1", GitCommit:"aa98e7e3dd2356bce72e8e367e8c87e8085c692b", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:27:55Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS Kops Cluster

**Comment by bacongobbler** [comment]
I'm not seeing this with v2.10.0-rc.2. Can you confirm?>

**Comment by sudermanjr** [comment]
Yep, this is fixed in rc.2.  Thanks.
