### ISSUE TITLE
helm generate --force prints out templates

### ISSUE THREAD

**Issue by bacongobbler** [helm/helm#442]
I don't think this is intentional:

```
><> helm generate workflow-dev --force
#helm:generate helm tpl $HELM_GENERATE_DIR/tpl/deis-controller-secret-builder-key-auth.yaml --out $HELM_GENERATE_DIR/manifests/deis-controller-secret-builder-key-auth.yaml
apiVersion: v1
kind: Secret
metadata:
  name: builder-key-auth
  namespace: deis
  labels:
    heritage: deis
type: Opaque
data:
  builder-key: QTlYXSdNfFJ+V1FZZ3NQaH4tJGZeIlI9NXZEYW99ZT1aY1plYzY/NkkvLlV6d1R1bDQ0bkB1SjdHJ1JDSzZ6ew==
#helm:generate helm tpl $HELM_GENERATE_DIR/tpl/deis-controller-secret-django-secret-key.yaml --out $HELM_GENERATE_DIR/manifests/deis-controller-secret-django-secret-key.yaml
apiVersion: v1
kind: Secret
metadata:
  name: django-secret-key
  namespace: deis
  labels:
    heritage: deis
type: Opaque
data:
  secret-key: cjBDOHFVOFlEU0pkRlRmZUReOyonTUZQa2tGdz0pUDsrRUB8fXI5YC9eLE1rZHQvekFdMUZASzVDUm5hInNHKQ==
#helm:generate helm tpl $HELM_GENERATE_DIR/tpl/deis-database-secret-creds.yaml --out $HELM_GENERATE_DIR/manifests/deis-database-secret-creds.yaml
apiVersion: v1
kind: Secret
metadata:
  name: database-creds
  namespace: deis
  labels:
    app: deis-database
    heritage: deis
data:
  user: ckFYMEppOFJ5cnY0a2NXWVQ1cDkxSlJoVGNWVFRsVzU=
  password: NGlZRElBU3Fub3NoQXFPQTFqS1FEMnlWVU02akdOaFg=
---> Ran 13 generators.
```

**Comment by bacongobbler** [comment]
It looks like v0.6.0 isn't templating secrets at all. They're just printed to stdout.

**Comment by bacongobbler** [comment]
Found the issue after turning on --debug in the template itself:

```
[DEBUG] File: /home/bacongobbler/.helm/workspace/charts/workflow-dev/tpl/deis-controller-secret-django-secret-key.yaml, Command: helm --debug tpl /home/bacongobbler/.helm/workspace/charts/workflow-dev/tpl/deis-controller-secret-django-secret-key.yaml --out /home/bacongobbler/.helm/workspace/charts/workflow-dev/manifests/deis-controller-secret-django-secret-key.yaml
[ERROR] File /home/bacongobbler/.helm/workspace/charts/workflow-dev/manifests/deis-controller-secret-django-secret-key.yaml already exists. To overwrite it, please re-run this command with the --force/-f flag.
panic: File /home/bacongobbler/.helm/workspace/charts/workflow-dev/manifests/deis-controller-secret-django-secret-key.yaml already exists. To overwrite it, please re-run this command with the --force/-f flag.

goroutine 1 [running]:
panic(0xae6780, 0xc820298510)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/helm/helm/log.Die(0xc8201a96c0, 0xc9, 0x0, 0x0, 0x0)
        /home/bacongobbler/go/src/github.com/helm/helm/log/log.go:46 +0xe1
github.com/helm/helm/cli.glob.func13(0xc8201def00)
        /home/bacongobbler/go/src/github.com/helm/helm/cli/template.go:66 +0x2a3
github.com/helm/helm/vendor/github.com/codegangsta/cli.Command.Run(0xd5e6f0, 0x8, 0x0, 0x0, 0x139edc0, 0x1, 0x1, 0xe026e0, 0x21, 0x0, ...)
        /home/bacongobbler/go/src/github.com/helm/helm/vendor/github.com/codegangsta/cli/command.go:179 +0x1399
github.com/helm/helm/vendor/github.com/codegangsta/cli.(*App).Run(0xc8202138c0, 0xc82000a0c0, 0x6, 0x6, 0x7efdcf87c028, 0xc820298520)
        /home/bacongobbler/go/src/github.com/helm/helm/vendor/github.com/codegangsta/cli/app.go:196 +0x137c
github.com/helm/helm/vendor/github.com/codegangsta/cli.(*App).RunAndExitOnError(0xc8202138c0)
        /home/bacongobbler/go/src/github.com/helm/helm/vendor/github.com/codegangsta/cli/app.go:207 +0x54
main.main()
        /home/bacongobbler/go/src/github.com/helm/helm/helm.go:6 +0x25
[ERROR] Failed to complete generation: failed to execute helm --debug tpl /home/bacongobbler/.helm/workspace/charts/workflow-dev/tpl/deis-controller-secret-django-secret-key.yaml --out /home/bacongobbler/.helm/workspace/charts/workflow-dev/manifests/deis-controller-secret-django-secret-key.yaml (/home/bacongobbler/.helm/workspace/charts/workflow-dev/tpl/deis-controller-secret-django-secret-key.yaml): exit status 2
```

So it looks like a chicken-and-egg problem. We need to enable --force to `helm template` if `helm generate` has `--force` enabled.

**Comment by smothiki** [comment]
Helm generate -f is working even helm template -f its a behavior from codegansta cli where it considers the value we are giving next to a flag is the value provided to that flag 
For example:
```
$ helm template -f -o deis-database-secret-creds.yaml  /Users/smothiki/.helm/workspace/charts/workflow-dev/tpl/deis-database-secret-creds.yaml 
smothikis-MacBook-Pro:helm smothiki$ cat deis-database-secret-creds.yaml 
#helm:generate helm tpl $HELM_GENERATE_DIR/tpl/deis-database-secret-creds.yaml --out $HELM_GENERATE_DIR/manifests/deis-database-secret-creds.yaml
apiVersion: v1
kind: Secret
metadata:
  name: database-creds
  namespace: deis
  labels:
    app: deis-database
    heritage: deis
data:
  user: ZVplM08zaEVzSDFvb2VkT3RaMnVXT01IbUthV0FhSHU=
  password: a0wwQ0cyU2xsVDJUZ3RTUTVJdkNsS3FLSGR0WWZzUGs=
```
works because after -f there -o another flag 
```
 helm template -f /Users/smothiki/.helm/workspace/charts/workflow-dev/tpl/deis-database-secret-creds.yaml -o deis-database-secret-creds.yaml  
#helm:generate helm tpl $HELM_GENERATE_DIR/tpl/deis-database-secret-creds.yaml --out $HELM_GENERATE_DIR/manifests/deis-database-secret-creds.yaml
apiVersion: v1
kind: Secret
metadata:
  name: database-creds
  namespace: deis
  labels:
    app: deis-database
    heritage: deis
data:
  user: SURsaUU0UGpibnY2YklaRGJmSEFncFdSRk5ERzhTU2k=
  password: YUFSVGh1TlZPVHI3cE9rMVVjQk5EVTNTbnRQcFJLWVc=
```
the above command doesnt work cause it thinks   /Users/smothiki/.helm/workspace/charts/workflow-dev/tpl/deis-database-secret-creds.yaml  is a value to the flag -f . which messes up stuff . Either we have to change the commands in the deis charts or execute -f at the end .

**Comment by bacongobbler** [comment]
I've got a fix incoming

**Comment by bacongobbler** [comment]
turns out it's our own incorrect usage of `helm tpl` in our charts. The fix is in https://github.com/deis/charts/pull/239. Closing!
