### ISSUE TITLE
2.10-rc3: Fatal error in Bash for Windows

### ISSUE THREAD

**Issue by bjornmagnusson** [helm/helm#4467]
Running `helm` in Bash for Windows crashes. Even just `helm` without command crashes

runtime: epollwait on fd 4 failed with 38
fatal error: runtime: netpoll failed

runtime stack:
runtime.throw(0x161e726, 0x17)
        /usr/local/go/src/runtime/panic.go:616 +0x81
runtime.netpoll(0xc04c9384e00, 0xd00000000)
        /usr/local/go/src/runtime/netpoll_epoll.go:75 +0x216
runtime.sysmon()
        /usr/local/go/src/runtime/proc.go:4265 +0x424
runtime.mstart1(0x0)
        /usr/local/go/src/runtime/proc.go:1227 +0xe7
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1193 +0x76

goroutine 1 [chan receive, locked to thread]:
k8s.io/helm/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Register(0xc420451180, 0x174a3c0, 0xc420376000, 0x0, 0x0)
        /go/src/k8s.io/helm/vendor/github.com/prometheus/client_golang/prometheus/registry.go:298 +0x1ea
k8s.io/helm/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc420451180, 0xc4200a6750, 0x1, 0x1)
        /go/src/k8s.io/helm/vendor/github.com/prometheus/client_golang/prometheus/registry.go:403 +0x6f
k8s.io/helm/vendor/github.com/prometheus/client_golang/prometheus.MustRegister(0xc4200a6750, 0x1, 0x1)
        /go/src/k8s.io/helm/vendor/github.com/prometheus/client_golang/prometheus/registry.go:152 +0x53
k8s.io/helm/vendor/github.com/prometheus/client_golang/prometheus.init.0()
        /go/src/k8s.io/helm/vendor/github.com/prometheus/client_golang/prometheus/registry.go:53 +0x101

goroutine 18 [chan receive]:
k8s.io/helm/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x20b2ba0)
        /go/src/k8s.io/helm/vendor/github.com/golang/glog/glog.go:879 +0x8b
created by k8s.io/helm/vendor/github.com/golang/glog.init.0
        /go/src/k8s.io/helm/vendor/github.com/golang/glog/glog.go:410 +0x203

goroutine 23 [syscall]:
os/signal.signal_recv(0xc420191ec0)
        /usr/local/go/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 33 [runnable]:
k8s.io/helm/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Register.func1(0x174a3c0, 0xc420376000, 0xc420478000)
        /go/src/k8s.io/helm/vendor/github.com/prometheus/client_golang/prometheus/registry.go:291
created by k8s.io/helm/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Register
        /go/src/k8s.io/helm/vendor/github.com/prometheus/client_golang/prometheus/registry.go:291 +0x14e

Output of `helm version`:
Client: 2.10-rc3

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:17:47Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Docker for Windows
Client in Bash for Windows

Related issue: https://github.com/docker/for-linux/issues/399

**Comment by bacongobbler** [comment]
I can't seem to reproduce, so it might be local to your system.

```
><> wget https://storage.googleapis.com/kubernetes-helm/helm-v2.10.0-rc.3-linux-amd64.tar.gz
--2018-08-14 08:12:31--  https://storage.googleapis.com/kubernetes-helm/helm-v2.10.0-rc.3-linux-amd64.tar.gz
Resolving storage.googleapis.com (storage.googleapis.com)... 216.58.193.80, 2607:f8b0:400a:800::2010
Connecting to storage.googleapis.com (storage.googleapis.com)|216.58.193.80|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9206272 (8.8M) [application/x-tar]
Saving to: ‘helm-v2.10.0-rc.3-linux-amd64.tar.gz’

helm-v2.10.0-rc.3-linux-amd64 100%[=================================================>]   8.78M  17.8MB/s    in 0.5s

2018-08-14 08:12:32 (17.8 MB/s) - ‘helm-v2.10.0-rc.3-linux-amd64.tar.gz’ saved [9206272/9206272]

><> tar xf helm-v2.10.0-rc.3-linux-amd64.tar.gz
><> ls
code  helm-v2.10.0-rc.3-linux-amd64.tar.gz  linux-amd64
><> ./linux-amd64/helm version -c
Client: &version.Version{SemVer:"v2.10.0-rc.3", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```

**Comment by bjornmagnusson** [comment]
Can reproduce issues with 2.9.0 and 2.9.1 as well. 2.8.2 is the last version actually working, and without problems.

For 2.9.x:
runtime: epollwait on fd 4 failed with 38
fatal error: runtime: netpoll failed

runtime stack:
runtime.throw(0x1619770, 0x17)
        /usr/local/go/src/runtime/panic.go:616 +0x81
runtime.netpoll(0x4dfd905b8600, 0xd00000000)
        /usr/local/go/src/runtime/netpoll_epoll.go:75 +0x216
runtime.sysmon()
        /usr/local/go/src/runtime/proc.go:4265 +0x424
runtime.mstart1(0x0)
        /usr/local/go/src/runtime/proc.go:1227 +0xe7
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1193 +0x76

goroutine 1 [runnable, locked to thread]:
k8s.io/helm/vendor/k8s.io/apimachinery/pkg/runtime.(*Scheme).AddKnownTypeWithName(0xc4200810c0, 0x1614f04, 0x14, 0x1605b88, 0x7, 0x12f45bd, 0x17, 0x1746420, 0xc4200bb7c0)
        /go/src/k8s.io/helm/vendor/k8s.io/apimachinery/pkg/runtime/scheme.go:194 +0x277
k8s.io/helm/vendor/k8s.io/apimachinery/pkg/runtime.(*Scheme).AddKnownTypes(0xc4200810c0, 0x1614f04, 0x14, 0x1605b88, 0x7, 0xc4204d88a8, 0x4, 0x4)
        /go/src/k8s.io/helm/vendor/k8s.io/apimachinery/pkg/runtime/scheme.go:167 +0x168
k8s.io/helm/vendor/k8s.io/api/authorization/v1beta1.addKnownTypes(0xc4200810c0, 0x0, 0x0)
        /go/src/k8s.io/helm/vendor/k8s.io/api/authorization/v1beta1/register.go:46 +0x165
k8s.io/helm/vendor/k8s.io/apimachinery/pkg/runtime.(*SchemeBuilder).AddToScheme(0x20a9d80, 0xc4200810c0, 0x0, 0x0)
        /go/src/k8s.io/helm/vendor/k8s.io/apimachinery/pkg/runtime/scheme_builder.go:29 +0x6d
k8s.io/helm/vendor/k8s.io/apimachinery/pkg/runtime.(*SchemeBuilder).AddToScheme-fm(0xc4200810c0, 0x0, 0x0)
        /go/src/k8s.io/helm/vendor/k8s.io/api/core/v1/register.go:41 +0x34
k8s.io/helm/vendor/k8s.io/client-go/kubernetes/scheme.AddToScheme(0xc4200810c0)
        /go/src/k8s.io/helm/vendor/k8s.io/client-go/kubernetes/scheme/register.go:88 +0xde
k8s.io/helm/vendor/k8s.io/kubernetes/pkg/kubectl/scheme.init.0()
        /go/src/k8s.io/helm/vendor/k8s.io/kubernetes/pkg/kubectl/scheme/install.go:60 +0x85

goroutine 5 [chan receive]:
k8s.io/helm/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x20abb20)
        /go/src/k8s.io/helm/vendor/github.com/golang/glog/glog.go:879 +0x8b
created by k8s.io/helm/vendor/github.com/golang/glog.init.0
        /go/src/k8s.io/helm/vendor/github.com/golang/glog/glog.go:410 +0x203

goroutine 7 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x41

**Comment by bacongobbler** [comment]
Closing due to inactivity. Please open a new ticket against Helm 3 if this issue persists. Thanks!
