### ISSUE TITLE
Segmentation fault running "helm list" when there are 0 releases

### ISSUE THREAD

**Issue by tmlbl** [helm/helm#4550]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.10.0-rc.1", GitCommit:"aa98e7e3dd2356bce72e8e367e8c87e8085c692b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0-rc.1", GitCommit:"aa98e7e3dd2356bce72e8e367e8c87e8085c692b", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
Using Minikube

`helm list` appears to work fine, but when I have no releases, this happens:
```
$ helm list
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x127dab6]

goroutine 1 [running]:
main.(*listCmd).run(0xc4200d75f0, 0xc42074a600, 0x1399960)
	/home/tim/go/src/k8s.io/helm/cmd/helm/list.go:170 +0x266
main.newListCmd.func2(0xc4208b4240, 0x20e64d8, 0x0, 0x0, 0x0, 0x0)
	/home/tim/go/src/k8s.io/helm/cmd/helm/list.go:117 +0x46
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).execute(0xc4208b4240, 0x20e64d8, 0x0, 0x0, 0xc4208b4240, 0x20e64d8)
	/home/tim/go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:599 +0x3db
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42093e000, 0xc420894b40, 0xc420894fc0, 0xc420895680)
	/home/tim/go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:689 +0x2d4
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42093e000, 0x1, 0x1)
	/home/tim/go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
	/home/tim/go/src/k8s.io/helm/cmd/helm/helm.go:160 +0x75
```

**Comment by tmlbl** [comment]
Sorry, this was on an out-of-date build of the master branch. Appears to be resolved now.
