### ISSUE TITLE
panic: interface conversion when doing helm upgrade --install via concourse

### ISSUE THREAD

**Issue by AndrewMorsillo** [helm/helm#4582]
On GKE installing via concourse the install process bombs out. This was working previously until I made some changes to my cluster. I switched my nodes from cos to ubuntu and upgraded to the latest Kubernetes version on GKE.

Kubectl version:
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platfo
rm:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.6-gke.2", GitCommit:"384b4eaa132ca9a295fcb3e5dfc74062b257e7df", GitTreeState:"clean", BuildDate:"2018-08-15T00:10:14Z", GoVersion:"go1.9.3b4", Compiler:"
gc", Platform:"linux/amd64"}
```

Helm version:
```
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}

```

Stack trace:
```
Running command helm upgrade taskhero-staging /tmp/build/put/helm-repo/taskhero-0.1.0.tgz --tiller-namespace=kube-system -f /tmp/build/put/chart-source/staging.yaml --set image.repository=gcr.io/taskhero-197200/taskhero-staging --set image.digest=sha256:2c27459820b97667af265c84d9fcf04afe89089cc28bee15b85af347ea69acf6 --set env.APP_VERSION=latest --install --namespace staging | tee /tmp/log
Release "taskhero-staging" does not exist. Installing it now.

panic: interface conversion: interface {} is []interface {}, not map[string]interface {}

goroutine 1 [running]:
k8s.io/helm/pkg/strvals.(*parser).key(0xc42066ef60, 0xc4204d68d0, 0x1214aad, 0x14d70c0)
	/go/src/k8s.io/helm/pkg/strvals/parser.go:211 +0xebc
k8s.io/helm/pkg/strvals.(*parser).parse(0xc42066ef60, 0xc4204d68d0, 0x0)
	/go/src/k8s.io/helm/pkg/strvals/parser.go:133 +0x38
k8s.io/helm/pkg/strvals.ParseInto(0x7ffed89d9ea4, 0x16, 0xc4204d68d0, 0x0, 0x0)
	/go/src/k8s.io/helm/pkg/strvals/parser.go:85 +0xbf
main.vals(0xc42052cfe0, 0x1, 0x1, 0xc42007f6c0, 0x3, 0x4, 0x20d7238, 0x0, 0x0, 0x20d7238, ...)
	/go/src/k8s.io/helm/cmd/helm/install.go:382 +0x45a
main.(*installCmd).run(0xc420b7db68, 0xc42000c018, 0x163e75e)
	/go/src/k8s.io/helm/cmd/helm/install.go:232 +0x1e4
main.(*upgradeCmd).run(0xc420001980, 0x0, 0x1778080)
	/go/src/k8s.io/helm/cmd/helm/upgrade.go:202 +0xe3f
main.newUpgradeCmd.func2(0xc420769d40, 0xc4206b41c0, 0x2, 0xe, 0x0, 0x0)
	/go/src/k8s.io/helm/cmd/helm/upgrade.go:117 +0x141
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).execute(0xc420769d40, 0xc4206b40e0, 0xe, 0xe, 0xc420769d40, 0xc4206b40e0)
	/go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:599 +0x3db
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4207d4000, 0xc4207426c0, 0xc420742fc0, 0xc420743680)
	/go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:689 +0x2d4
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4207d4000, 0xf, 0xf)
	/go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
	/go/src/k8s.io/helm/cmd/helm/helm.go:161 +0x79


```

**Comment by AndrewMorsillo** [comment]
OK I figured out what was wrong. The error message is totally unhelpful. I had an invalid --set where I was setting an array instead of a position in that array. Perhaps helm should catch this and spit out an error instead of bombing?

**Comment by ryanberger-az** [comment]
@AndrewMorsillo thank you so much, we were tracking down a similar issue and your follow up comment helped us get around it & resolve it. agreed, this error message is really really misleading and led us down a totally wrong path.
