### ISSUE TITLE
helm list: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ozbillwang** [helm/helm#4814]
Output of `helm version`:

```
$ helm version
Client: &version.Version{SemVer:"v2.10.0-rc.1", GitCommit:"aa98e7e3dd2356bce72e8e367e8c87e8085c692b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0-rc.1", GitCommit:"aa98e7e3dd2356bce72e8e367e8c87e8085c692b", GitTreeState:"clean"}

```
Output of `kubectl version`:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:20:58Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

    minikube

Get panic error:

```
$ helm list
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1e767d6]

goroutine 1 [running]:
main.(*listCmd).run(0xc4200ce630, 0xc420916600, 0x1f907c0)
	/go/src/k8s.io/helm/cmd/helm/list.go:170 +0x266
main.newListCmd.func2(0xc420772000, 0x2cd4ae8, 0x0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/helm/cmd/helm/list.go:117 +0x46
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).execute(0xc420772000, 0x2cd4ae8, 0x0, 0x0, 0xc420772000, 0x2cd4ae8)
	/go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:599 +0x3db
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4207cc240, 0xc420747440, 0xc420747d40, 0xc42073c240)
	/go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:689 +0x2d4
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4207cc240, 0x1, 0x1)
	/go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
	/go/src/k8s.io/helm/cmd/helm/helm.go:160 +0x75

```

**Comment by bacongobbler** [comment]
can you try v2.10.0 or v2.11.0? Pretty sure this was fixed after v2.10.0-rc.1.
