### ISSUE TITLE
ref(status): introduce a `FlatRelease` struct for structured output

### ISSUE THREAD

**Issue by bacongobbler** [helm/helm#5456]
`helm status` should use a JSON form of the Release object for formatting rather than stripping information out of the Release object for general consumption.

See https://github.com/helm/helm/pull/5455 for a potential solution.

**Comment by arief-hidayat** [comment]
Hi,
I am interested to start contributing. Has someone started working on this issue?

Thanks

**Comment by bacongobbler** [comment]
Hi there! Yes, this is something that I've started work on. This is strictly for the Helm 3 branch so it doesn't apply to Helm 2. Sorry!

**Comment by arief-hidayat** [comment]
no problem. thanks

**Comment by avinashdhinwa** [comment]
@bacongobbler  Isn't this issue closed?

**Comment by kvendingoldo** [comment]
I'll fix it

**Comment by kvendingoldo** [comment]
@bacongobbler why are you done rel.Chart = nil? I have changed the log level of outfmt.Write object and in this case, we will see issue instead of `MANIFEST` field:

```
NAME: test-1572726287
LAST DEPLOYED: Sun Nov  3 00:24:48 2019
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
null

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1f30027]

goroutine 1 [running]:
helm.sh/helm/v3/pkg/chartutil.coalesceValues(0x0, 0xc00028f2c0)
        /Users/kvendingoldo/go/src/github.com/helm/helm/pkg/chartutil/coalesce.go:154 +0x37
helm.sh/helm/v3/pkg/chartutil.coalesce(0x0, 0xc00028f2c0, 0x2305fa0, 0x0, 0x2305fa0)
        /Users/kvendingoldo/go/src/github.com/helm/helm/pkg/chartutil/coalesce.go:60 +0x35
helm.sh/helm/v3/pkg/chartutil.CoalesceValues(0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/kvendingoldo/go/src/github.com/helm/helm/pkg/chartutil/coalesce.go:50 +0x97
main.statusPrinter.WriteTable(0xc00054a150, 0x388e001, 0x2784da0, 0xc0000d4000, 0xc00079fc80, 0x2125a05)
        /Users/kvendingoldo/go/src/github.com/helm/helm/cmd/helm/status.go:126 +0xbe3
helm.sh/helm/v3/pkg/cli/output.Format.Write(0x2521f70, 0x5, 0x2784da0, 0xc0000d4000, 0x27bce20, 0xc000511010, 0x4, 0x11e3490)
        /Users/kvendingoldo/go/src/github.com/helm/helm/pkg/cli/output/output.go:56 +0xad
main.newStatusCmd.func1(0xc000154780, 0xc0003f6f70, 0x1, 0x1, 0x0, 0x0)
        /Users/kvendingoldo/go/src/github.com/helm/helm/cmd/helm/status.go:63 +0x10d
github.com/spf13/cobra.(*Command).execute(0xc000154780, 0xc0003f6ef0, 0x1, 0x1, 0xc000154780, 0xc0003f6ef0)
        /Users/kvendingoldo/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002dca00, 0x27c32a0, 0xc00026e160, 0x25244f9)
        /Users/kvendingoldo/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/kvendingoldo/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /Users/kvendingoldo/go/src/github.com/helm/helm/cmd/helm/helm.go:75 +0x204
```

If we will comment line `rel.Chart = nil` we will see the next:

```
NAME: test-1572726287
LAST DEPLOYED: Sun Nov  3 00:24:48 2019
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
null

COMPUTED VALUES:
workers:
  first_worker:
    replicas: 1

HOOKS:
MANIFEST:
---
# Source: test/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: first-deployment
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: gcr.io/google_samples/gb-frontend:v3
        ports:
        - containerPort: 80
```

**Comment by bacongobbler** [comment]
closing as inactive.
