### ISSUE TITLE
 SIGSEGV: segmentation violation when helm repo add

### ISSUE THREAD

**Issue by voron** [helm/helm#5537]
Just hit a SIGSEGV while `repo add`
```
helm repo add elastic https://helm.elastic.co
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x3e0018 pc=0x7fff96b0b4dd]

runtime stack:
runtime.throw(0x239263d, 0x2a)
        /usr/local/Cellar/go/1.12.1/libexec/src/runtime/panic.go:617 +0x72
runtime.sigpanic()
        /usr/local/Cellar/go/1.12.1/libexec/src/runtime/signal_unix.go:374 +0x4a9

goroutine 25 [syscall]:
runtime.cgocall(0x1001900, 0xc000757470, 0xc000744cb8)
        /usr/local/Cellar/go/1.12.1/libexec/src/runtime/cgocall.go:128 +0x5b fp=0xc000757440 sp=0xc000757408 pc=0x100502b
crypto/x509._Cfunc_FetchPEMRoots(0xc000744cb0, 0xc000744cb8, 0xc000400600, 0x0)
        _cgo_gotypes.go:110 +0x4d fp=0xc000757470 sp=0xc000757440 pc=0x1355fcd
crypto/x509.loadSystemRoots.func1(0xc000744cb0, 0xc000744cb8, 0x101922f)
        /usr/local/Cellar/go/1.12.1/libexec/src/crypto/x509/root_cgo_darwin.go:281 +0x12d fp=0xc0007574b0 sp=0xc000757470 pc=0x135b9dd
crypto/x509.loadSystemRoots(0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.12.1/libexec/src/crypto/x509/root_cgo_darwin.go:281 +0xec fp=0xc000757580 sp=0xc0007574b0 pc=0x135613c
crypto/x509.initSystemRoots()
        /usr/local/Cellar/go/1.12.1/libexec/src/crypto/x509/root.go:21 +0x26 fp=0xc0007575a8 sp=0xc000757580 pc=0x1344076
sync.(*Once).Do(0x359fd80, 0x240bf48)
        /usr/local/Cellar/go/1.12.1/libexec/src/sync/once.go:44 +0xb3 fp=0xc0007575d8 sp=0xc0007575a8 pc=0x1063bc3
crypto/x509.systemRootsPool(...)
        /usr/local/Cellar/go/1.12.1/libexec/src/crypto/x509/root.go:16
crypto/x509.(*Certificate).Verify(0xc0001d8b00, 0xc0005bc2e0, 0xf, 0xc0004c1650, 0x0, 0xbf20f17b16eb4388, 0x3aaac3123, 0x357c000, 0x0, 0x0, ...)
        /usr/local/Cellar/go/1.12.1/libexec/src/crypto/x509/verify.go:744 +0x6ca fp=0xc0007576f0 sp=0xc0007575d8 pc=0x134899a
crypto/tls.(*Conn).verifyServerCertificate(0xc000717880, 0xc0004c1140, 0x2, 0x2, 0xb52, 0x0)
        /usr/local/Cellar/go/1.12.1/libexec/src/crypto/tls/handshake_client.go:838 +0x26a fp=0xc000757888 sp=0xc0007576f0 pc=0x138096a
crypto/tls.(*clientHandshakeState).doFullHandshake(0xc000757dc8, 0xc0005ba0e0, 0x6a)
        /usr/local/Cellar/go/1.12.1/libexec/src/crypto/tls/handshake_client.go:454 +0x1869 fp=0xc000757bc0 sp=0xc000757888 pc=0x137eab9
crypto/tls.(*clientHandshakeState).handshake(0xc000757dc8, 0xc00025a000, 0x0)
        /usr/local/Cellar/go/1.12.1/libexec/src/crypto/tls/handshake_client.go:399 +0x3fb fp=0xc000757cc8 sp=0xc000757bc0 pc=0x137ce7b
crypto/tls.(*Conn).clientHandshake(0xc000717880, 0x0, 0x0)
        /usr/local/Cellar/go/1.12.1/libexec/src/crypto/tls/handshake_client.go:208 +0x2cd fp=0xc000757f38 sp=0xc000757cc8 pc=0x137b4cd
crypto/tls.(*Conn).Handshake(0xc000717880, 0x0, 0x0)
        /usr/local/Cellar/go/1.12.1/libexec/src/crypto/tls/conn.go:1343 +0xef fp=0xc000757f78 sp=0xc000757f38 pc=0x1379adf
net/http.(*persistConn).addTLS.func2(0x0, 0xc000717880, 0x0, 0xc0003995c0)
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/transport.go:1190 +0x42 fp=0xc000757fc0 sp=0xc000757f78 pc=0x1466db2
runtime.goexit()
        /usr/local/Cellar/go/1.12.1/libexec/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000757fc8 sp=0xc000757fc0 pc=0x105aee1
created by net/http.(*persistConn).addTLS
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/transport.go:1186 +0x1ab

goroutine 1 [select]:
net/http.(*Transport).getConn(0xc000256900, 0xc000543080, 0x0, 0xc000146300, 0x5, 0xc0005bc2e0, 0x13, 0x0, 0x0, 0x0, ...)
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/transport.go:1020 +0x63d
net/http.(*Transport).roundTrip(0xc000256900, 0xc0000ffd00, 0x10, 0xc0004bc8b0, 0xc00065f4a0)
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/transport.go:467 +0x6ef
net/http.(*Transport).RoundTrip(0xc000256900, 0xc0000ffd00, 0xc000256900, 0x0, 0x0)
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/roundtrip.go:17 +0x35
net/http.send(0xc0000ffd00, 0x259fa00, 0xc000256900, 0x0, 0x0, 0x0, 0xc0000d41a8, 0xc00065f6c8, 0x1, 0x0)
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/client.go:250 +0x461
net/http.(*Client).send(0xc000542e70, 0xc0000ffd00, 0x0, 0x0, 0x0, 0xc0000d41a8, 0x0, 0x1, 0x357d400)
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/client.go:174 +0xfb
net/http.(*Client).do(0xc000542e70, 0xc0000ffd00, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/client.go:641 +0x279
net/http.(*Client).Do(...)
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/client.go:509
k8s.io/helm/pkg/getter.(*HttpGetter).get(0xc000542e40, 0xc000146300, 0x22, 0xc000146300, 0x22, 0x40)
        /private/tmp/kubernetes-helm-20190315-55017-1pnmaqo/src/k8s.io/helm/pkg/getter/httpgetter.go:63 +0x25d
k8s.io/helm/pkg/getter.(*HttpGetter).Get(0xc000542e40, 0xc000146300, 0x22, 0x2366b34, 0xb, 0x2366b34)
        /private/tmp/kubernetes-helm-20190315-55017-1pnmaqo/src/k8s.io/helm/pkg/getter/httpgetter.go:45 +0x3f
k8s.io/helm/pkg/repo.(*ChartRepository).DownloadIndexFile(0xc00030d3c0, 0xc000202060, 0x23, 0x2, 0x2)
        /private/tmp/kubernetes-helm-20190315-55017-1pnmaqo/src/k8s.io/helm/pkg/repo/chartrepo.go:124 +0x19a
main.addRepository(0x7fff5fbffabe, 0x7, 0x7fff5fbffac6, 0x17, 0x0, 0x0, 0x0, 0x0, 0xc0000d22c0, 0x12, ...)
        /private/tmp/kubernetes-helm-20190315-55017-1pnmaqo/src/k8s.io/helm/cmd/helm/repo_add.go:130 +0x4a8
main.(*repoAddCmd).run(0xc0001befa0, 0xc00065fd80, 0x2)
        /private/tmp/kubernetes-helm-20190315-55017-1pnmaqo/src/k8s.io/helm/cmd/helm/repo_add.go:88 +0x11a
main.newRepoAddCmd.func1(0xc0004b2f00, 0xc0004c37e0, 0x2, 0x2, 0x0, 0x0)
        /private/tmp/kubernetes-helm-20190315-55017-1pnmaqo/src/k8s.io/helm/cmd/helm/repo_add.go:62 +0xfd
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).execute(0xc0004b2f00, 0xc0004c3740, 0x2, 0x2, 0xc0004b2f00, 0xc0004c3740)
        /private/tmp/kubernetes-helm-20190315-55017-1pnmaqo/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:762 +0x465
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000552280, 0x4, 0x4, 0xc000552280)
        /private/tmp/kubernetes-helm-20190315-55017-1pnmaqo/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /private/tmp/kubernetes-helm-20190315-55017-1pnmaqo/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:800
main.main()
        /private/tmp/kubernetes-helm-20190315-55017-1pnmaqo/src/k8s.io/helm/cmd/helm/helm.go:171 +0x7a

goroutine 34 [chan receive]:
k8s.io/helm/vendor/k8s.io/klog.(*loggingT).flushDaemon(0x357c480)
        /private/tmp/kubernetes-helm-20190315-55017-1pnmaqo/src/k8s.io/helm/vendor/k8s.io/klog/klog.go:941 +0x8b
created by k8s.io/helm/vendor/k8s.io/klog.init.0
        /private/tmp/kubernetes-helm-20190315-55017-1pnmaqo/src/k8s.io/helm/vendor/k8s.io/klog/klog.go:403 +0x6c

goroutine 4 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/Cellar/go/1.12.1/libexec/src/runtime/sigqueue.go:139 +0x9f
os/signal.loop()
        /usr/local/Cellar/go/1.12.1/libexec/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/local/Cellar/go/1.12.1/libexec/src/os/signal/signal_unix.go:29 +0x41

goroutine 7 [chan receive]:
net/http.(*persistConn).addTLS(0xc0002418c0, 0xc0005bc2e0, 0xf, 0x0, 0xc0005bc2f0, 0x3)
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/transport.go:1196 +0x1d4
net/http.(*Transport).dialConn(0xc000256900, 0x25cf340, 0xc0000e8000, 0x0, 0xc000146300, 0x5, 0xc0005bc2e0, 0x13, 0x0, 0x1006ec5, ...)
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/transport.go:1269 +0x1cde
net/http.(*Transport).getConn.func4(0xc000256900, 0x25cf340, 0xc0000e8000, 0xc0005430b0, 0xc0000eac60)
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/transport.go:1015 +0xa6
created by net/http.(*Transport).getConn
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/transport.go:1014 +0x455
```
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-20T19:19:32Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-gke.7", GitCommit:"aeaa96020ec0614a8773799058c3b8d58c19b9ff", GitTreeState:"clean", BuildDate:"2019-03-13T11:22:57Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

**Comment by SlickNik** [comment]
Hi @voron -- thanks for reporting this!
Just to clarify, did this happen just the once or is it consistent? FWIW, I tried to reproduce the issue, and wasn't able to.

Also, from reading the stack trace, the issue seems to have possibly been triggered by the `crypto/x509` code during the TLS handshake verification. Was there something strange with redirects / certs that you can think of when this happened?

Thanks!

**Comment by voron** [comment]
It looks like build/OS problems, similar to [this](https://github.com/golang/go/issues/28092). I've tried helm v13.1, no luck. I've upgraded OS and the problem is gone w/o any rebuild.

**Comment by SlickNik** [comment]
Thanks for the follow up!
