### ISSUE TITLE
tiller nil reference with `helm upgrade --install --atomic ...`

### ISSUE THREAD

**Issue by lodejard** [helm/helm#6061]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): aks-engine

In a continuous deployment scenario a `stable/prometheus-operator` chart with fairly default values is rolled out with `helm upgrade --install --atomic` switches. There are fairly regular transient failures - but just this morning one of the failures produced a fault call stack that was pretty interesting.

It seems like it's possible for the call to `u.client.ReleaseHistory` to fail in a way that continues executing. This is an upgrade, not an install. But later at upgrade.go line 290 tiller instance crashes during rollback because the `releaseHistory` must have been returned as null.

https://github.com/helm/helm/blob/79d07943b03aea2b76c12644b4b54733bc5958d6/cmd/helm/upgrade.go#L197
https://github.com/helm/helm/blob/79d07943b03aea2b76c12644b4b54733bc5958d6/cmd/helm/upgrade.go#L290

It does appear that the function structure is still the same in the current code.

https://github.com/helm/helm/blob/master/cmd/helm/upgrade.go#L199
https://github.com/helm/helm/blob/master/cmd/helm/upgrade.go#L295

Console output from build agent
```
2019-07-22T16:50:25.2831415Z E0722 16:50:25.282672    5132 portforward.go:391] an error occurred forwarding 43423 -> 44134: error forwarding port 44134 to pod 4b9875db46a1d50928db75076f9792bab88582f521c96ab67ec8d1e9cfcaab6a, uid : exit status 1: 2019/07/22 16:50:25 socat[12192] E connect(5, AF=2 127.0.0.1:44134, 16): Connection refused
2019-07-22T16:50:26.3833936Z E0722 16:50:26.382696    5132 portforward.go:391] an error occurred forwarding 43423 -> 44134: error forwarding port 44134 to pod 4b9875db46a1d50928db75076f9792bab88582f521c96ab67ec8d1e9cfcaab6a, uid : exit status 1: 2019/07/22 16:50:26 socat[12235] E connect(5, AF=2 127.0.0.1:44134, 16): Connection refused
2019-07-22T16:50:28.3842424Z E0722 16:50:28.383662    5132 portforward.go:391] an error occurred forwarding 43423 -> 44134: error forwarding port 44134 to pod 4b9875db46a1d50928db75076f9792bab88582f521c96ab67ec8d1e9cfcaab6a, uid : exit status 1: 2019/07/22 16:50:28 socat[12314] E connect(5, AF=2 127.0.0.1:44134, 16): Connection refused
2019-07-22T16:50:53.1289799Z UPGRADE FAILED
2019-07-22T16:50:53.1292116Z ROLLING BACK
2019-07-22T16:50:53.1292635Z Error: transport is closing
2019-07-22T16:50:53.1313428Z panic: runtime error: invalid memory address or nil pointer dereference
2019-07-22T16:50:53.1329034Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x137ec3a]
2019-07-22T16:50:53.1329346Z 
2019-07-22T16:50:53.1329710Z goroutine 1 [running]:
2019-07-22T16:50:53.1330087Z main.(*upgradeCmd).run(0xc0002ebe00, 0x0, 0x18b9f20)
2019-07-22T16:50:53.1330343Z 	/go/src/k8s.io/helm/cmd/helm/upgrade.go:290 +0xada
2019-07-22T16:50:53.1330608Z main.newUpgradeCmd.func2(0xc000678f00, 0xc0006c4000, 0x2, 0x13, 0x0, 0x0)
2019-07-22T16:50:53.1330873Z 	/go/src/k8s.io/helm/cmd/helm/upgrade.go:148 +0x149
2019-07-22T16:50:53.1331171Z k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).execute(0xc000678f00, 0xc0003f7e00, 0x13, 0x14, 0xc000678f00, 0xc0003f7e00)
2019-07-22T16:50:53.1331464Z 	/go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:762 +0x473
2019-07-22T16:50:53.1331772Z k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000414500, 0xc0006b4f00, 0xc0006b5180, 0xc0006b5400)
2019-07-22T16:50:53.1332061Z 	/go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
2019-07-22T16:50:53.1332632Z k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).Execute(0xc000414500, 0x14, 0x15)
2019-07-22T16:50:53.1332903Z 	/go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:800 +0x2b
2019-07-22T16:50:53.1333553Z main.main()
2019-07-22T16:50:53.1333910Z 	/go/src/k8s.io/helm/cmd/helm/helm.go:171 +0x79
```

**Comment by bacongobbler** [comment]
https://github.com/helm/helm/pull/5395 may be relevant here.

**Comment by lodejard** [comment]
Some additional details. On the cluster in question `helm list --all` shows this release is PENDING_ROLLBACK.

```
>helm list --all
NAME                                            REVISION        UPDATED                         STATUS                  CHART                                   APP VERSION     NAMESPACE
external-dns                                    55              Mon Jul 22 09:54:24 2019        DEPLOYED                external-dns-2.0.2                      0.5.15          redacted-namespace
prometheus-operator                             27              Mon Jul 22 09:52:56 2019        PENDING_ROLLBACK        prometheus-operator-5.14.1              0.31.1          redacted-namespace
```

Other deployments like `external-dns` appear to be fine.

```
>helm history external-dns --max=4
REVISION        UPDATED                         STATUS          CHART                   DESCRIPTION
52              Sat Jul 20 20:47:10 2019        SUPERSEDED      external-dns-2.0.2      Upgrade complete
53              Mon Jul 22 07:44:21 2019        SUPERSEDED      external-dns-2.0.2      Upgrade complete
54              Mon Jul 22 08:05:22 2019        SUPERSEDED      external-dns-2.0.2      Upgrade complete
55              Mon Jul 22 09:54:24 2019        DEPLOYED        external-dns-2.0.2      Upgrade complete
```

However fetching history of `prometheus-operator` seems to be able to cause the pod to terminate.

this worked
```
>helm history prometheus-operator --max=4
REVISION        UPDATED                         STATUS                  CHART                           DESCRIPTION
24              Sat Jul 20 12:38:41 2019        SUPERSEDED              prometheus-operator-5.14.1      Upgrade complete
25              Sat Jul 20 20:18:24 2019        DEPLOYED                prometheus-operator-5.14.1      Rollback to 24
26              Sat Jul 20 20:42:09 2019        PENDING_ROLLBACK        prometheus-operator-5.14.1      Rollback to 25
27              Mon Jul 22 09:52:56 2019        PENDING_ROLLBACK        prometheus-operator-5.14.1      Rollback to 26
```

this failed
```
>helm history prometheus-operator
Error: transport is closing
```

the tiller pod stops suddenly when history without `--max` is requested
```
>kubectl logs tiller-deploy-7cfbd67c77-cs2zw -f
[main] 2019/07/22 18:08:54 Starting Tiller v2.13.0 (tls=false)
[main] 2019/07/22 18:08:54 GRPC listening on :44134
[main] 2019/07/22 18:08:54 Probes listening on :44135
[main] 2019/07/22 18:08:54 Storage driver is ConfigMap
[main] 2019/07/22 18:08:54 Max history per release is 200
[tiller] 2019/07/22 18:09:08 getting history for release external-dns
[storage] 2019/07/22 18:09:08 getting release history for "external-dns"
[tiller] 2019/07/22 18:09:37 getting history for release external-dns
[storage] 2019/07/22 18:09:37 getting release history for "external-dns"
[storage] 2019/07/22 18:09:56 listing all releases with filter
[tiller] 2019/07/22 18:12:42 getting history for release external-dns
[storage] 2019/07/22 18:12:42 getting release history for "external-dns"
[tiller] 2019/07/22 18:14:31 getting history for release prometheus-operator
[storage] 2019/07/22 18:14:31 getting release history for "prometheus-operator"
[tiller] 2019/07/22 18:14:59 getting history for release prometheus-operator
[storage] 2019/07/22 18:14:59 getting release history for "prometheus-operator"
>(the -f streaming stopped at this point)
```

**Comment by lodejard** [comment]
Hi @bacongobbler - thanks for the note but I'm not sure if it's related. I'm beginning to suspect that the tiller pod's memory limit is too low (150Mi) and it is being terminated while executing the history request.

If that's the case - there is still a valid helm client-side bug here. If it gets an err other than not-installed when listing history then shouldn't proceed with the upgrade. It will subsequently fail on the nil reference if it needs to roll back.

**Comment by lodejard** [comment]
I see you've added a `question/support` label to this issue. But there is actually a helm client-side bug at https://github.com/helm/helm/blob/master/cmd/helm/upgrade.go#L199 that will let err cases through resulting in a nil `releaseHistory` which will crash later in the function.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Comment by bacongobbler** [comment]
Note: with the removal of Tiller in Helm 3, this codepath has likely been removed/fixed.
