### ISSUE TITLE
[Helm3] Helm3 install results in panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by sidharthsurana** [helm/helm#6677]
Output of `helm version`: 
version.BuildInfo{Version:"v3.0.0-beta.4", GitCommit:"7ffc879f137bd3a69eea53349b01f05e3d1d2385", GitTreeState:"dirty", GoVersion:"go1.13.1"}

Ran into the Nil Pointer error when doing a `helm3 install <chart name> `. The chart used here is a helm2 chart loaded from a helm repo.

Note: the same chart if I were to extract locally on the filesystem and then use the same command it works. 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x11234bb]

goroutine 1 [running]:
helm.sh/helm/v3/pkg/chart/loader.LoadFiles(0xc0002cd000, 0x110, 0x200, 0x110, 0x200, 0x0)
	/home/circleci/helm.sh/helm/pkg/chart/loader/load.go:107 +0xafb
helm.sh/helm/v3/pkg/chart/loader.LoadArchive(0x1bd0780, 0xc000588020, 0x0, 0xc000000000, 0xc000588020)
	/home/circleci/helm.sh/helm/pkg/chart/loader/archive.go:147 +0x87
helm.sh/helm/v3/pkg/chart/loader.LoadFile(0xc001d44000, 0x38, 0x0, 0x0, 0x0)
	/home/circleci/helm.sh/helm/pkg/chart/loader/archive.go:58 +0x1df
helm.sh/helm/v3/pkg/chart/loader.FileLoader.Load(...)
	/home/circleci/helm.sh/helm/pkg/chart/loader/archive.go:41
helm.sh/helm/v3/pkg/chart/loader.Load(0xc001d44000, 0x38, 0x1, 0x1, 0xc00190a450)
	/home/circleci/helm.sh/helm/pkg/chart/loader/load.go:62 +0x79
main.runInstall(0xc0000ec8f0, 0x2, 0xb, 0xc0001c8900, 0xc0005116e0, 0x1bd07a0, 0xc0000c6008, 0x1968a38, 0x4, 0x5d6d90)
	/home/circleci/helm.sh/helm/cmd/helm/install.go:174 +0x369
main.newInstallCmd.func1(0xc0002e7680, 0xc0000ec8f0, 0x2, 0xb, 0x0, 0x0)
	/home/circleci/helm.sh/helm/cmd/helm/install.go:115 +0x83
github.com/spf13/cobra.(*Command).execute(0xc0002e7680, 0xc0000ec840, 0xb, 0xb, 0xc0002e7680, 0xc0000ec840)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004f0280, 0x1bd0700, 0xc0000c6008, 0xc0000aec40)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:80 +0xd1
```

Looking at the error trace I have narrowed the issue to be an incorrectly ordered check below:
https://github.com/helm/helm/blob/7ffc879f137bd3a69eea53349b01f05e3d1d2385/pkg/chart/loader/load.go#L107-L112

The nil check needs to be above APIVersion check.
I built a local helm3 client with the reversed order and that seems to fix the issue.
I will post a patch shortly

**Comment by hickeyma** [comment]
@sidharthsurana Thanks for raising this issue.

I have tried to reproduce it as follows:

```console
$ helm repo list
NAME  	URL                                              
stable	https://kubernetes-charts.storage.googleapis.com/

$ helm install mysql stable/mysql
NAME: mysql
LAST DEPLOYED: Wed Oct 16 10:12:44 2019
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
MySQL can be accessed via port 3306 on the following DNS name from within your cluster:
mysql.default.svc.cluster.local
[....]

$ helm ls
NAME     	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART          	APP VERSION
chrt-test	default  	1       	2019-10-14 16:15:07.404097887 +0100 IST	deployed	chrt-test-0.1.0	1.16.0     
foo      	default  	1       	2019-10-16 10:06:43.306564136 +0100 IST	deployed	foo-0.1.0      	1.0        
mysql    	default  	1       	2019-10-16 10:12:44.973783872 +0100 IST	deployed	mysql-1.4.0    	5.7.27 
```

Do you mind providing more details on how to reproduce this issue?

**Comment by sfright** [comment]
I am seeing similar behavior to OP, Unfortunately cannot provide the chart details here.

`version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}`

Do not see this issue if i extract the chart contents locally and attempt to deploy, but if i try and pull from the remote repository i receive runtime error. 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x12d939c]

goroutine 1 [running]:
helm.sh/helm/v3/pkg/chart/loader.LoadFiles(0xc0000d2a00, 0x15, 0x20, 0x15, 0x20, 0x0)
	/home/circleci/helm.sh/helm/pkg/chart/loader/load.go:126 +0xa9c
helm.sh/helm/v3/pkg/chart/loader.LoadArchive(0x1d28e00, 0xc000656010, 0xc000656010, 0x0, 0x0)
	/home/circleci/helm.sh/helm/pkg/chart/loader/archive.go:193 +0x87
helm.sh/helm/v3/pkg/chart/loader.LoadFile(0xc000722090, 0x30, 0x0, 0x0, 0x0)
	/home/circleci/helm.sh/helm/pkg/chart/loader/archive.go:65 +0x221
helm.sh/helm/v3/pkg/chart/loader.FileLoader.Load(...)
	/home/circleci/helm.sh/helm/pkg/chart/loader/archive.go:43
helm.sh/helm/v3/pkg/chart/loader.Load(0xc000722090, 0x30, 0x1, 0x1, 0xc0006e2870)
	/home/circleci/helm.sh/helm/pkg/chart/loader/load.go:62 +0x79
main.runInstall(0xc000212960, 0x2, 0x5, 0xc0009cdbc0, 0xc0000eb200, 0x1d28e20, 0xc00000e018, 0x32, 0x0, 0x0)
	/home/circleci/helm.sh/helm/cmd/helm/install.go:185 +0x369
main.newUpgradeCmd.func1(0xc000415340, 0xc000212960, 0x2, 0x5, 0x0, 0x0)
	/home/circleci/helm.sh/helm/cmd/helm/upgrade.go:104 +0xa22
github.com/spf13/cobra.(*Command).execute(0xc000415340, 0xc0002128c0, 0x5, 0x5, 0xc000415340, 0xc0002128c0)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc00025b340, 0x1d6bc40, 0xc000456210, 0xc0004f9250)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:83 +0x206

```

**Comment by guice** [comment]
I'm runing into this issue with the latest helm 3.7 
```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}
```

Error: 
```
bash-5.1# helm package -u sample-service --app-version master-3ccfc7e
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1a20f8e]

goroutine 1 [running]:
helm.sh/helm/v3/pkg/chart.(*Chart).Name(...)
        helm.sh/helm/v3/pkg/chart/chart.go:76
helm.sh/helm/v3/pkg/downloader.(*Manager).safeMoveDeps(0xc0001161b0, 0xc0049d8360, 0x3, 0x3, 0xc0020e65a0, 0x22, 0xc00133ed00, 0x1f, 0x37, 0xc0036b0150)
        helm.sh/helm/v3/pkg/downloader/manager.go:452 +0x46e
helm.sh/helm/v3/pkg/downloader.(*Manager).downloadAll(0xc0001161b0, 0xc0049d8360, 0x3, 0x3, 0x0, 0x0)
        helm.sh/helm/v3/pkg/downloader/manager.go:371 +0x671
helm.sh/helm/v3/pkg/downloader.(*Manager).Update(0xc0001161b0, 0xc0001161b0, 0x225ac48)
        helm.sh/helm/v3/pkg/downloader/manager.go:201 +0x1b7
main.newPackageCmd.func1(0xc0000eaf00, 0xc0004f5440, 0x1, 0x4, 0x0, 0x0)
        helm.sh/helm/v3/cmd/helm/package.go:99 +0x431
github.com/spf13/cobra.(*Command).execute(0xc0000eaf00, 0xc0004f5400, 0x4, 0x4, 0xc0000eaf00, 0xc0004f5400)
        github.com/spf13/cobra@v1.2.1/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000072a00, 0xc00000f000, 0x1, 0xc0005b1f60)
        github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
        helm.sh/helm/v3/cmd/helm/helm.go:87 +0x27b
```
