### ISSUE TITLE
panic: unexpected error: pipe: too many open files

### ISSUE THREAD

**Issue by mhyousefi** [helm/helm#7382]
I am trying to apply a `helmfile` containing about 60 Node JS and Python micro-services. It used to work smoothly before. Recently, though, I am getting the following error:

```
Building dependency release=release-1, chart=charts/common
Building dependency release=release-2, chart=charts/common
.
.
.
Building dependency release=release-60, chart=charts/common
Comparing release=release-1, chart=charts/common
Comparing release=release-2, chart=charts/common
.
.
.
Comparing release=release-60, chart=charts/common
panic: unexpected error: pipe: too many open files

goroutine 639 [running]:
github.com/roboll/helmfile/pkg/helmexec.combinedOutput(0xc0003102c0, 0xc000010310, 0x54, 0xc0005b5a40, 0xc000396000, 0x54, 0x80)
	/private/tmp/helmfile-20191228-17879-w4r5zy/helmfile-0.98.1/pkg/helmexec/runner.go:69 +0x45a
github.com/roboll/helmfile/pkg/helmexec.ShellRunner.Execute(0x0, 0x0, 0xc000010310, 0x1f49ba4, 0x4, 0xc00001ac30, 0xf, 0xf, 0xc0005b5a40, 0x100bb2b, ...)
	/private/tmp/helmfile-20191228-17879-w4r5zy/helmfile-0.98.1/pkg/helmexec/runner.go:36 +0xd9
github.com/roboll/helmfile/pkg/helmexec.(*execer).exec(0xc00040e000, 0xc00001ac30, 0xf, 0xf, 0xc0005b5a40, 0x9, 0x10, 0x9, 0x0, 0x0)
	/private/tmp/helmfile-20191228-17879-w4r5zy/helmfile-0.98.1/pkg/helmexec/exec.go:329 +0x370
github.com/roboll/helmfile/pkg/helmexec.(*execer).DiffRelease(0xc00040e000, 0x0, 0x0, 0x0, 0xa, 0x27, 0xc00035ef20, 0x15, 0xc00003af50, 0xd, ...)
	/private/tmp/helmfile-20191228-17879-w4r5zy/helmfile-0.98.1/pkg/helmexec/exec.go:262 +0x367
github.com/roboll/helmfile/pkg/state.(*HelmState).DiffReleases.func2(0x27)
	/private/tmp/helmfile-20191228-17879-w4r5zy/helmfile-0.98.1/pkg/state/state.go:1127 +0x2b6
github.com/roboll/helmfile/pkg/state.(*HelmState).scatterGather.func1(0xc000438900, 0xc00050adf8, 0xc0004e4c00, 0xc00050ae00, 0x27)
	/private/tmp/helmfile-20191228-17879-w4r5zy/helmfile-0.98.1/pkg/state/state_run.go:42 +0x124
created by github.com/roboll/helmfile/pkg/state.(*HelmState).scatterGather
	/private/tmp/helmfile-20191228-17879-w4r5zy/helmfile-0.98.1/pkg/state/state_run.go:40 +0x1bc
```

Well, I can apply my releases half at a time, but I suppose this should not be the case.
Any help is appreciated.

Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

Output of `kubectl version` : 
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-11T12:34:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by andytom** [comment]
It looks like this panic comes from [helmfile](https://github.com/roboll/helmfile) not helm, have you tried opening an issue there?

**Comment by mhyousefi** [comment]
I wasn't sure which repo it was more relevant to. I'll post an issue on the `Helmfile` repo as well.

**Comment by bacongobbler** [comment]
The stack trace is pointing at helmfile’s code. Please follow up there. Closing!
