### ISSUE TITLE
Helm cannot install the package

### ISSUE THREAD

**Issue by li-sen** [helm/helm#7798]
Output of `helm version`:
helm version
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

ERROR:

helm install --name mongodb-test --namespace=xx-test -f custom.yaml .
Error: grpc: received message larger than max (213582628 vs. 20971520)

I tried to change the source code and recompile it, but the compilation failed.

vim pkg/helm/client.go
const maxMsgSize = 1024 * 1024 * 200
vim pkg/tiller/server.go
const maxMsgSize = 1024 * 1024 * 200

```
INFO] --> Exporting gopkg.in/gorp.v1
[INFO] --> Exporting sigs.k8s.io/yaml
[INFO] --> Exporting vbom.ml/util
[INFO] --> Exporting sigs.k8s.io/kustomize
[INFO] --> Exporting github.com/DATA-DOG/go-sqlmock
[INFO] --> Exporting github.com/pmezard/go-difflib
[INFO] --> Exporting github.com/stretchr/testify
[INFO] Replacing existing vendor dependencies
[INFO] Removing nested vendor and Godeps/_workspace directories...
[INFO] Removing: /root/workspace/go/src/k8s.io/helm/vendor/github.com/cpuguy83/go-md2man/vendor
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x6fdc82]

goroutine 1 [running]:
github.com/Masterminds/glide/path.StripVendor.func1(0xc42038cc60, 0x59, 0x0, 0x0, 0x8f3160, 0xc4201c4db0, 0x0, 0x0)
 /home/vagrant/go/src/github.com/Masterminds/glide/path/strip.go:28 +0x42
path/filepath.walk(0xc4203d54a0, 0x4e, 0x8fa0e0, 0xc4203508f0, 0xc4202cc000, 0x0, 0x0)
 /usr/lib/go-1.10/src/path/filepath/path.go:377 +0x20d
path/filepath.walk(0xc4203d4e10, 0x47, 0x8fa0e0, 0xc4201e9790, 0xc4202cc000, 0x0, 0x0)
 /usr/lib/go-1.10/src/path/filepath/path.go:381 +0x2c2
path/filepath.walk(0xc420460540, 0x3d, 0x8fa0e0, 0xc4201e96c0, 0xc4202cc000, 0x0, 0x0)
 /usr/lib/go-1.10/src/path/filepath/path.go:381 +0x2c2
path/filepath.walk(0xc420460400, 0x34, 0x8fa0e0, 0xc420719e10, 0xc4202cc000, 0x0, 0x0)
 /usr/lib/go-1.10/src/path/filepath/path.go:381 +0x2c2
path/filepath.walk(0xc4208a6270, 0x29, 0x8fa0e0, 0xc4207c0410, 0xc4202cc000, 0x0, 0x20)
 /usr/lib/go-1.10/src/path/filepath/path.go:381 +0x2c2
path/filepath.Walk(0xc4208a6270, 0x29, 0xc4202cc000, 0xc4207c0340, 0x0)
 /usr/lib/go-1.10/src/path/filepath/path.go:403 +0x106
github.com/Masterminds/glide/path.StripVendor(0x8b0354, 0x3b)
 /home/vagrant/go/src/github.com/Masterminds/glide/path/strip.go:22 +0x10a
github.com/Masterminds/glide/action.Install(0xc4201b4580, 0x89bc01)
 /home/vagrant/go/src/github.com/Masterminds/glide/action/install.go:62 +0x35b
main.commands.func12(0xc4200d6f20, 0x0, 0xc4200d6f20)
 /home/vagrant/go/src/github.com/Masterminds/glide/glide.go:510 +0x2bf
github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.HandleAction(0x811280, 0x8ba950, 0xc4200d6f20, 0xc42006b200, 0x0)
 /home/vagrant/go/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/app.go:490 +0xc8
github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.Command.Run(0x899e45, 0x7, 0x8984a0, 0x1, 0x0, 0x0, 0x0, 0x8a58b2, 0x20, 0x0, ...)
 /home/vagrant/go/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/command.go:210 +0xa36
github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.(*App).Run(0xc42008aea0, 0xc42001e090, 0x3, 0x3, 0x0, 0x0)
 /home/vagrant/go/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/app.go:255 +0x6a0
main.main()
 /home/vagrant/go/src/github.com/Masterminds/glide/glide.go:104 +0x5a9
Makefile:174: recipe for target 'bootstrap' failed
make: *** [bootstrap] Error 2
root@free01:~/workspace/go/src/k8s.io/helm# git branch
* (HEAD detached at v2.16.3)
  master
```

**Comment by li-sen** [comment]
It's my problem. There is a big file in the package directory.
