### ISSUE TITLE
Exception when using --values and --set referencing the same value

### ISSUE THREAD

**Issue by kkendzia** [helm/helm#8388]
Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Bare Metal / Kind

I want to upgrade/install a chart with this line:

`helm upgrade -in artis-dev --create-namespace --values ../profiles/dev.yaml --set environment.ARTICLE_LISTENER_OPTIONS="--every-nth-element 50" article-listener article-listener/`

dev.yaml content:

```
environment:
  - name: ARTICLE_LISTENER_OPTIONS
    value: "--every-nth-element 100"
  - name: ES_JAVA_OPTS
    value: "-Xms2g -Xmx2g"
```
dev.yaml is the default environment and is set with every local deployment. When I want to reassign a value which already exists in this file I get following exception:

```
panic: interface conversion: interface {} is []interface {}, not map[string]interface {}

goroutine 1 [running]:
helm.sh/helm/v3/pkg/strvals.(*parser).key(0xc00076eb00, 0xc00074d7a0, 0x1661e0d, 0x1932c40)
        /home/circleci/helm.sh/helm/pkg/strvals/parser.go:211 +0xdea
helm.sh/helm/v3/pkg/strvals.(*parser).parse(0xc00076eb00, 0xc00074d7a0, 0x0)
        /home/circleci/helm.sh/helm/pkg/strvals/parser.go:133 +0x38
helm.sh/helm/v3/pkg/strvals.ParseInto(0x7ffe6397a26a, 0x3b, 0xc00074d7a0, 0x17aa2e0, 0xc00000f8c8)
        /home/circleci/helm.sh/helm/pkg/strvals/parser.go:70 +0xbe
helm.sh/helm/v3/pkg/cli/values.(*Options).MergeValues(0xc0006be5a0, 0xc00076e880, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/circleci/helm.sh/helm/pkg/cli/values/options.go:62 +0x22b
main.newUpgradeCmd.func1(0xc0006d8dc0, 0xc0001126c0, 0x2, 0x9, 0x0, 0x0)
        /home/circleci/helm.sh/helm/cmd/helm/upgrade.go:124 +0x325
github.com/spf13/cobra.(*Command).execute(0xc0006d8dc0, 0xc000112480, 0x9, 0x9, 0xc0006d8dc0, 0xc000112480)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc0006ba000, 0x1d6bd60, 0xc00044a160, 0x7ffe6397a229)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:83 +0x206
```

Is it a duplicate of #7184 ?

**Comment by bacongobbler** [comment]
Edited the original comment for improved readability with backquotes.

**Comment by bacongobbler** [comment]
In your dev.yaml, you specified the values under the `environment` as an array. In your `--set` arguments, you provided it as a dictionary.

To fix this, use the following syntax in your dev.yaml:

```
environment:
  ARTICLE_LISTENER_OPTIONS: "--every-nth-element 100"
  ES_JAVA_OPTS: "-Xms2g -Xmx2g"
```

**Comment by mattfarina** [comment]
@kkendzia First, Helm could have a better error message for this. This is coming from internal mechanisms and isn't all that user friendly. I can see why this is hard to figure out.

The `name` and `value` you're adding in there isn't needed. `--set` works on the structure as is.
