### ISSUE TITLE
Panic occurs when calling helm list function

### ISSUE THREAD

**Issue by sharadregoti** [helm/helm#9085]
Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}
```

Output of `kubectl version`:

```Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): minikube
minikube version: 

```
minikube version: v1.15.1
commit: 23f40a012abb52eff365ff99a709501a61ac5876
```

This is my list function,

```
func HelmList() error {
	settings := cli.New()
	actionConfig := new(action.Configuration)
	if err := actionConfig.Init(settings.RESTClientGetter(), settings.Namespace(), os.Getenv("HELM_DRIVER"), log.Printf); err != nil {
		return err
	}
	lCli := action.NewChartList(actionConfig)
	if err := lCli.Run(os.Stdout); err != nil {
		return err
	}
	return nil
}
```

When calling this function, panic occurs & this is the output, all function such as install, uninstall & action.NewList(actionConfig) are working for me.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x162bbba]

goroutine 1 [running]:
helm.sh/helm/v3/internal/experimental/registry.(*Client).getChartTableRows(0x0, 0xc000829c60, 0x6, 0x6, 0xc000829c18, 0x7fef8c49da00)
        /home/sharad/spaceup/backend/space-cloud/space-cli/vendor/helm.sh/helm/v3/internal/experimental/registry/client.go:251 +0x3a
helm.sh/helm/v3/internal/experimental/registry.(*Client).PrintChartTable(0x0, 0x1e3dba0, 0xc0005ac160)
        /home/sharad/spaceup/backend/space-cloud/space-cli/vendor/helm.sh/helm/v3/internal/experimental/registry/client.go:229 +0x1a7
helm.sh/helm/v3/pkg/action.(*ChartList).Run(...)
        /home/sharad/spaceup/backend/space-cloud/space-cli/vendor/helm.sh/helm/v3/pkg/action/chart_list.go:37
github.com/spaceuptech/space-cloud/space-cli/cmd/utils.HelmList(0x0, 0x0)
        /home/sharad/spaceup/backend/space-cloud/space-cli/cmd/utils/helm.go:66 +0x10c
github.com/spaceuptech/space-cloud/space-cli/cmd/modules/operations.actionList(0xc000542b00, 0x2bdd778, 0x0, 0x0, 0x0, 0x0)
        /home/sharad/spaceup/backend/space-cloud/space-cli/cmd/modules/operations/commands.go:203 +0x25
github.com/spf13/cobra.(*Command).execute(0xc000542b00, 0x2bdd778, 0x0, 0x0, 0xc000542b00, 0x2bdd778)
        /home/sharad/spaceup/backend/space-cloud/space-cli/vendor/github.com/spf13/cobra/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003b6dc0, 0x0, 0xffffffff, 0xc00004a1d8)
        /home/sharad/spaceup/backend/space-cloud/space-cli/vendor/github.com/spf13/cobra/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/sharad/spaceup/backend/space-cloud/space-cli/vendor/github.com/spf13/cobra/command.go:887
main.main()
        /home/sharad/spaceup/backend/space-cloud/space-cli/main.go:21 +0x2a
```

EDIT: updated by @bacongobbler for improved readability.

**Comment by bacongobbler** [comment]
You're attempting to call the API for `helm chart list`. Is that intentional?

Change `action.NewChartList` with `action.NewList` as per https://helm.sh/docs/topics/advanced/#simple-example.

**Comment by bacongobbler** [comment]
To clarify on the error, you're receiving that because `helm init` was never called yet, and `helm chart list` is attempting to read Helm's config directory which does not exist.

**Comment by sharadregoti** [comment]
@bacongobbler My bad, I wanted to list all the installed charts. changing action.NewChartList with action.NewList worked for me :+1: 
Thanks

**Comment by sTb1337** [comment]
Thanks @sharadregoti, you helped me there :)
