### ISSUE TITLE
OCI: Segfault on helm show chart 

### ISSUE THREAD

**Issue by arnisoph** [helm/helm#9515]
```
$ helm version
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.16"}
```

```
$ helm show chart oci://europe-west1-docker.pkg.dev/foo/external-dns:0.1.0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x21fd8a3]

goroutine 1 [running]:
helm.sh/helm/v3/internal/experimental/registry.(*Client).PullChart(0x0, 0xc000395860, 0xc000395860, 0x0, 0x0)
	/private/tmp/helm-20210310-51670-30olmy/internal/experimental/registry/client.go:156 +0x183
helm.sh/helm/v3/pkg/getter.(*OCIGetter).get(0xc000a6f360, 0xc000a76a20, 0x51, 0xc0005e3940, 0xc000a76a20, 0x51)
	/private/tmp/helm-20210310-51670-30olmy/pkg/getter/ocigetter.go:52 +0xc7
helm.sh/helm/v3/pkg/getter.(*OCIGetter).Get(0xc000a6f360, 0xc000a76a20, 0x51, 0xc000621bf0, 0x4, 0x6, 0xc000a6f360, 0x0, 0x0)
	/private/tmp/helm-20210310-51670-30olmy/pkg/getter/ocigetter.go:36 +0x77
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo(0xc0005e3bd8, 0x7ffeefbff750, 0x51, 0x0, 0x0, 0xc0002f8120, 0x28, 0x203000, 0x203000, 0x5, ...)
	/private/tmp/helm-20210310-51670-30olmy/pkg/downloader/chart_downloader.go:99 +0x142
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart(0xc0002e0f00, 0x7ffeefbff750, 0x51, 0xc0005cc000, 0x1, 0x24, 0xc0005c8780, 0xc0008add28)
	/private/tmp/helm-20210310-51670-30olmy/pkg/action/install.go:675 +0x412
main.runShow(0xc0006c68a0, 0x1, 0x1, 0xc0002e0f00, 0xc0000f4000, 0x27d74ce, 0x4, 0x11d0ce0)
	/private/tmp/helm-20210310-51670-30olmy/cmd/helm/show.go:179 +0xea
main.newShowCmd.func4(0xc0003c0000, 0xc0006c68a0, 0x1, 0x1, 0x0, 0x0)
	/private/tmp/helm-20210310-51670-30olmy/cmd/helm/show.go:116 +0x8a
github.com/spf13/cobra.(*Command).execute(0xc0003c0000, 0xc0006c6880, 0x1, 0x1, 0xc0003c0000, 0xc0006c6880)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0005c02c0, 0xc000010f18, 0x1, 0xc0008adf60)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main()
	/private/tmp/helm-20210310-51670-30olmy/cmd/helm/helm.go:80 +0x25b
```

Actually I'm not sure whether I'm invoking show chart with the correct syntax. There's almost no OCI-related docs for that on the net. :D

**Comment by bacongobbler** [comment]
`helm show` support has not yet been implemented. Only `helm pull` and `helm dependency update` were implemented in #8843 as far as I can tell.

Marking as a feature enhancement.

**Comment by arnisoph** [comment]
I consider nil pointer references as bugs. But I can see your point. 😅

**Comment by arnisoph** [comment]
issue might be still open, hope it will be fixed by the referenced PRs
