### ISSUE TITLE
issue: OCI dependency update when running `helm template`

### ISSUE THREAD

**Issue by tchupp** [helm/helm#9535]
Following [this guide](https://helm.sh/docs/topics/registries/#specifying-dependencies), I am trying to use a dependency I have in GitHub Container Registry. When trying to resolve the dependencies during `helm3 template`, I am encountering a panic. The same exact setup works when using `helm dependency update`.

Why is there a difference in these behaviors?

```
$ cat Chart.yaml
...
dependencies:
    - name: <chart name>
      version: "v1"
      repository: "oci://ghcr.io/<org>"

$ helm3 template --dependency-update .
Getting updates for unmanaged Helm repositories...
...Unable to get an update from the "oci://ghcr.io/<org>" chart repository:
        tag explicitly required
Saving 1 charts
Downloading <chart name> from repo oci://ghcr.io/<org>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x22105e3]

goroutine 1 [running]:
helm.sh/helm/v3/internal/experimental/registry.(*Client).PullChart(0x0, 0xc0003929a0, 0xc0003929a0, 0x0, 0x0)
        /private/tmp/helm-20210204-99981-1f8vc0y/internal/experimental/registry/client.go:156 +0x183
helm.sh/helm/v3/pkg/getter.(*OCIGetter).get(0xc000371680, 0xc00049f4a0, 0x22, 0xc00052f408, 0xc00049f4a0, 0x22)
        /private/tmp/helm-20210204-99981-1f8vc0y/pkg/getter/ocigetter.go:52 +0xc5
helm.sh/helm/v3/pkg/getter.(*OCIGetter).Get(0xc000371680, 0xc00049f4a0, 0x22, 0xc000392840, 0x4, 0x4, 0xc000371680, 0x0, 0x0)
        /private/tmp/helm-20210204-99981-1f8vc0y/pkg/getter/ocigetter.go:36 +0x77
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo(0xc00052f7b8, 0xc00049f440, 0x22, 0xc00049f463, 0x2, 0xc00010f860, 0x58, 0x4, 0x0, 0x0, ...)
        /private/tmp/helm-20210204-99981-1f8vc0y/pkg/downloader/chart_downloader.go:99 +0x13f
helm.sh/helm/v3/pkg/downloader.(*Manager).downloadAll(0xc0000edb00, 0xc0007186b0, 0x1, 0x1, 0xc0004d5710, 0xc0005ca3c0)
        /private/tmp/helm-20210204-99981-1f8vc0y/pkg/downloader/manager.go:354 +0xfd3
helm.sh/helm/v3/pkg/downloader.(*Manager).Update(0xc0000edb00, 0xc0000edb00, 0x1)
        /private/tmp/helm-20210204-99981-1f8vc0y/pkg/downloader/manager.go:201 +0x19e
main.runInstall(0xc0005bbbc0, 0x1, 0x4, 0xc0004eb7c0, 0xc0005c7740, 0x2a4fcc0, 0xc000198008, 0x8, 0xc00052fa98, 0x10af164)
        /private/tmp/helm-20210204-99981-1f8vc0y/cmd/helm/install.go:228 +0x507
main.newTemplateCmd.func2(0xc000252dc0, 0xc0005bbbc0, 0x1, 0x4, 0x0, 0x0)
        /private/tmp/helm-20210204-99981-1f8vc0y/cmd/helm/template.go:73 +0x134
github.com/spf13/cobra.(*Command).execute(0xc000252dc0, 0xc0005bbb80, 0x4, 0x4, 0xc000252dc0, 0xc0005bbb80)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000162840, 0xc000718400, 0x1, 0xc00052ff60)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main()
        /private/tmp/helm-20210204-99981-1f8vc0y/cmd/helm/helm.go:80 +0x24d

$ rm -rf tmpcharts/

$ helm3 dependency update
Getting updates for unmanaged Helm repositories...
...Unable to get an update from the "oci://ghcr.io/<org>" chart repository:
        tag explicitly required
Saving 1 charts
Downloading <chart name> from repo oci://ghcr.io/<org>
v1: Pulling from ghcr.io/<org>/<chart name>
Deleting outdated charts
```

Output of `helm version`:
```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"clean", GoVersion:"go1.15.7"}
```

**Comment by tchupp** [comment]
I was able to track down a weird issue, but I'm not sure why it's happening yet.
This line seems to be what is causing the panic: https://github.com/helm/helm/blob/master/internal/experimental/registry/client.go#L156
```go
func (c *Client) PullChart(ref *Reference) (*bytes.Buffer, error) {
	buf := bytes.NewBuffer(nil)

	if ref.Tag == "" {
		return buf, errors.New("tag explicitly required")
	}

	fmt.Fprintf(c.out, "%s: Pulling from %s\n", ref.Tag, ref.Repo) // panic is here
...
```

Since we know that `ref` isn't `nil`, I added an additional log line out of curiosity:
```go
func (c *Client) PullChart(ref *Reference) (*bytes.Buffer, error) {
	buf := bytes.NewBuffer(nil)

	if ref.Tag == "" {
		return buf, errors.New("tag explicitly required")
	}

	fmt.Fprintf(os.Stdout, "Using client %s\n", c) // new log line
	fmt.Fprintf(c.out, "%s: Pulling from %s\n", ref.Tag, ref.Repo)
...
```

and I was able to see this output:
```go
$ make build && ./bin/helm template --dependency-update <path to chart>
...Unable to get an update from the "oci://ghcr.io/<org>" chart repository:
        tag explicitly required
Saving 1 charts
Downloading /<chart name> from repo oci://ghcr.io/<org>
v1: Pulling from ghcr.io/<org>/<chart name>. With client: %!s(*registry.Client=<nil>)
Using client %!s(*registry.Client=<nil>)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2210a9f]
...
```

Somehow the registry client is getting set to `nil`!

**Comment by tchupp** [comment]
I added the following printf to the following function: https://github.com/helm/helm/blob/master/pkg/getter/ocigetter.go#L31
```go
//Get performs a Get from repo.Getter and returns the body.
func (g *OCIGetter) Get(href string, options ...Option) (*bytes.Buffer, error) {
	fmt.Fprintf(os.Stdout, "before opts: Pulling from %s. With client: %s\n", href, g.opts.registryClient)
	for _, opt := range options {
		opt(&g.opts)
	}
	fmt.Fprintf(os.Stdout, "after opts: Pulling from %s. With client: %s\n", href, g.opts.registryClient)
	return g.get(href)
}
```
And I can see the output:
```
$ make build && ./bin/helm template --dependency-update <path to chart>

Getting updates for unmanaged Helm repositories...

before opts: Pulling from oci://ghcr.io/<org>/index.yaml. With client: &{%!s(bool=false) /Users/<user>/Library/Caches/helm/registry/config.json %!s(*os.File=&{0xc000132060}) %!s(*registry.Authorizer=&{0xc00033eee0}) %!s(*registry.Resolver=&{0xc000597b00}) %!s(*registry.Cache=&{false 0xc000130008 /Users/<user>/Library/Caches/helm/registry/cache <nil> <nil>})}

after opts: Pulling from oci://ghcr.io/<org>/index.yaml. With client: &{%!s(bool=false) /Users/<user>/Library/Caches/helm/registry/config.json %!s(*os.File=&{0xc000132060}) %!s(*registry.Authorizer=&{0xc00033eee0}) %!s(*registry.Resolver=&{0xc000597b00}) %!s(*registry.Cache=&{false 0xc000130008 /Users/<user>/Library/Caches/helm/registry/cache <nil> <nil>})}

: Pulling from ghcr.io/<org>/index.yaml. With client: &{%!s(bool=false) /Users/<user>/Library/Caches/helm/registry/config.json %!s(*os.File=&{0xc000132060}) %!s(*registry.Authorizer=&{0xc00033eee0}) %!s(*registry.Resolver=&{0xc000597b00}) %!s(*registry.Cache=&{false 0xc000130008 /Users/<user>/Library/Caches/helm/registry/cache <nil> <nil>})}

...Unable to get an update from the "oci://ghcr.io/<org>" chart repository:
        tag explicitly required
Saving 1 charts

Downloading <chart name> from repo oci://ghcr.io/<org>

before opts: Pulling from oci://ghcr.io/<org>/<chart name>. With client: &{%!s(bool=false) /Users/<user>/Library/Caches/helm/registry/config.json %!s(*os.File=&{0xc000132060}) %!s(*registry.Authorizer=&{0xc00033f420}) %!s(*registry.Resolver=&{0xc000317920}) %!s(*registry.Cache=&{false 0xc000130008 /Users/<user>/Library/Caches/helm/registry/cache <nil> <nil>})}

after opts: Pulling from oci://ghcr.io/<org>/<chart name>. With client: %!s(*registry.Client=<nil>)

v1: Pulling from ghcr.io/<org>/<chart name>. With client: %!s(*registry.Client=<nil>)
Using client %!s(*registry.Client=<nil>)

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2210b29]
```
It appears that setting the options for the OCIGetter is setting the `registryClient` to `nil`

**Comment by mattfarina** [comment]
Let me first say, no matter what, you should not see a panic. So, I am marking this as a bug.

Did you enable OCI support? It's an experiment. See https://helm.sh/docs/topics/registries/#enabling-oci-support

**Comment by tchupp** [comment]
I tracked down the issue!!

When constructing the `download.Manager` for the install command, the `RegistryClient` is not set.

https://github.com/helm/helm/blob/master/cmd/helm/package.go#L88
```go
man := &downloader.Manager{
	Out:              out,
	ChartPath:        cp,
	Keyring:          client.ChartPathOptions.Keyring,
	SkipUpdate:       false,
	Getters:          p,
	RegistryClient:   client.cfg.RegistryClient,    // this was missing
	RepositoryConfig: settings.RepositoryConfig,
	RepositoryCache:  settings.RepositoryCache,
	Debug:            settings.Debug,
}
```

This won't exactly work, since `.cgf` isn't accessible from `package action`. I'm not 100% sure what the best way to do this would be, but I'll take a stab at a PR

**Comment by jdolitsky** [comment]
@tchupp - nice catch! Here's what I think needs to be done:

The `newPackageCmd` function here https://github.com/helm/helm/blob/master/cmd/helm/package.go#L51

should be modified to have signature `func (cfg *action.Configuration, out io.Writer) *cobra.Command`, such as here: https://github.com/helm/helm/blob/e8ac5b0aebe9e78d6bf90a7f218a39af577ac7e4/cmd/helm/dependency_build.go#L44

The cfg can then be passed in here which contains a RegistryClient: https://github.com/helm/helm/blob/e8ac5b0aebe9e78d6bf90a7f218a39af577ac7e4/cmd/helm/root.go#L174

**Comment by tchupp** [comment]
I've opened the PR here: https://github.com/helm/helm/pull/9539
I didn't address the `package` command yet, since that involved updating some tests and I wasn't confident about that change.
