### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\u2388' in position [Helm dep update command]

### ISSUE THREAD

**Issue by shahriak** [helm/helm#9615]
I am running into a stranger error after adding Helm dep update repo_name to update dependencies to my script and helm repo update:
Here's the commands I am using:

```
Write-Host "Helm Init..."
helm init --stable-repo-url=https://charts.helm.sh/stable --client-only --skip-refresh
Check-LastExitCode
helm repo update
Write-Host "Helm Init Complete!"

# update dependencies
Write-Host "helm repo remove local"
helm repo remove local

Write-Host "helm dep update $helmChartEv2Path"
helm dep update $helmChartEv2Path --skip-refresh
Check-LastExitCode

```
Error:
2021-04-16 20:42:03.864776: Helm Init...
2021-04-16 20:42:03.913741: Creating /root/.helm
2021-04-16 20:42:03.913970: Creating /root/.helm/repository
2021-04-16 20:42:03.914002: Creating /root/.helm/repository/cache
2021-04-16 20:42:03.914072: Creating /root/.helm/repository/local
2021-04-16 20:42:03.914192: Creating /root/.helm/plugins
2021-04-16 20:42:03.914228: Creating /root/.helm/starters
2021-04-16 20:42:03.914334: Creating /root/.helm/cache/archive
2021-04-16 20:42:03.914392: Creating /root/.helm/repository/repositories.yaml
2021-04-16 20:42:03.914418: Adding stable repo with URL: https://charts.helm.sh/stable
2021-04-16 20:42:03.914549: Adding local repo with URL: http://127.0.0.1:8879/charts
2021-04-16 20:42:03.915878: $HELM_HOME has been configured at /root/.helm.
2021-04-16 20:42:03.915937: Not installing Tiller due to 'client-only' flag having been set
2021-04-16 20:42:03.915954: Happy Helming!
2021-04-16 20:42:03.965335: Hang tight while we grab the latest from your chart repositories...
2021-04-16 20:42:03.965461: ...Skip local chart repository
2021-04-16 20:42:06.224685: ...Successfully got an update from the "stable" chart repository
Seed-2021-04-16 20:42:06.243130: Exception encountered
Seed-2021-04-16 20:42:06.243269: Error:
Traceback (most recent call last):
File "seed.py", line 54, in main
exitcode = launchpackage(unarchivedpath)
File "seed.py", line 144, in launchpackage
printwithdate(stroutline)
File "seed.py", line 161, in printwithdate
print("{}: {}".format(datetime.datetime.utcnow(), statement), flush=True)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2388' in position 45: ordinal not in range(128)
During handling of the above exception, another exception occurred:
File "seed.py", line 164, in
sys.exit(main())
File "seed.py", line 60, in main
printwithprefix(sys.exc_info())
File "seed.py", line 158, in printwithprefix
print("{}-{}: {}".format(seed_prefix, datetime.datetime.utcnow(), statement), flush=True)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2388' in position 138: ordinal not in range(128)

Output of `helm version`:

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"5de7fd1f9555368a86eb0f8f664dc58055c17269", GitTreeState:"clean", BuildDate:"2021-01-18T09:31:01Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS

**Comment by bacongobbler** [comment]
Looks like a python stack trace. Helm is written in Go.

What are you using to execute “seed.py”?

**Comment by shahriak** [comment]
> Looks like a python stack trace. Helm is written in Go.
> 
> What are you using to execute “seed.py”?

I do not have any python file references in my project. I am calling the helm commands on a PowerShell script. Could that be contributing to the issue?

**Comment by bacongobbler** [comment]
It's possible, yes. I've never heard of a PowerShell command called `Check-LastExitCode` before.

Usually I'll find scripts using this idiom:

```
If ($lastExitCode -eq "1") {
    Write-Host "helm init failed"
    [Environment]::Exit("1");
}
```

It is possible that `Check-LastExitCode` is a script written in Python. I would start investigating there.

Either way this is not a Helm issue, so I'm going to close this as we cannot help address this issue. But thank you for the report.
